aya-rs/aya

aya/src/bpf.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/mod.rs, aya/src/obj/mod.rs
Addresses #10 
Please note, while this passes tests I haven't had a chance to actually try it with an older/new map definitions. If someone has an old program lying around, please test it before merging.
It also breaks the `id` and `pinning` fields, replacing them with the members found [here](https://elixir.bootlin.com/linux/v5.12.12/source/include/uapi/linux/bpf.h#L491).
=> Support iproute2 bpf_map_def layout

bpf/aya-bpf/src/maps/mod.rs, bpf/aya-bpf/src/maps/stack_trace.rs
This path support initial support for BPF_MAP_TYPE_STACK_TRACE.
Signed-off-by: Tw <wei.tan@intel.com>
=> bpf: add support for STACK_TRACE map

bpf/aya-bpf/src/maps/stack_trace.rs
The type casting introduces an allocation, this will cause compiling failure when linking final bpf target.
So remove this casting to fix this issue.
BTW, the following is the failure I met:
```
= note: 07:24:12 [ERROR] fatal error: "unable to allocate function return #1"
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.    Running pass 'Function Pass Manager' on module 'trace_bpf-001a275b17e9eb12'.
1.    Running pass 'BPF DAG->DAG Pattern Instruction Selection' on function '@_ZN7aya_bpf4maps11stack_trace10StackTrace11get_stackid17h32b649bc3780c0aaE'
```
Signed-off-by: Tw <wei.tan@intel.com>
=> bpf: fix a minor bug due to stackid allocation

aya/src/bpf.rs, aya/src/obj/btf/relocation.rs
As per title, this PR changtes `Bpf::load` to use `Option<&Btf>` instead of `Option<Btf>` so that a single instance of Btf information can be shared among multiple programs, thus decreasing overall memory usage.
=> fix: pass BTF object by reference in order to allow multiple eBPF programs to share it and save memory (closes #30).

aya/src/programs/lirc_mode2.rs, aya/src/programs/mod.rs, aya/src/sys/bpf.rs
Signed-off-by: Sean Young <sean@mess.org>
=> Implement query for lirc programs

docs/src/start/development.md
`rustup install nightly --component rust-src`
gives:
```
error: Found argument '--component' which wasn't expected, or isn't valid in this context
USAGE:
rustup install [FLAGS] [OPTIONS] <toolchain>...
For more information try --help
```
The correct command seems to be `rustup toolchain install nightly --component rust-src`.
=> Fix rustup command in the docs.

docs/.gitignore, docs/book.toml, docs/src/SUMMARY.md, docs/src/start/development.md, docs/src/start/hello-xdp.md, docs/src/start/logging-packets.md
Continued the example by adding a PerfEventBuffer for logging packets.
@alessandrod when you get time to take a look, could you double check the code I'm using to cast `events` to `PacketLog` structs? `align_to` was the best I could figure, but I feel like there is a better way. I'm also thinking that it might make sense to have the full source code of each stage available somewhere....
=> docs: Logging Packets

aya/src/obj/btf/btf.rs, aya/src/obj/btf/relocation.rs, aya/src/obj/btf/types.rs, aya/src/programs/uprobe.rs
Seems the nightly clippy has found some dead code and issues with `manual implementation of split once`
This PR:
1. Ignores fields that aren't read (prefix field name with underscore)
2. Replaces `splitn` with `split_once`
=> Make Clippy Happy

.github/workflows/gen.yml, .gitignore
This commit adds a github action that will
- check out aya and libbpf
- run xtask codegen
- if there is a diff, commit changes to the codegen branch
- if changes were comitted, open a pull-request
Triggering is currently manual (via the `Actions`) tab or by REST API
Here's an example PR from this action: https://github.com/dave-tucker/aya/pull/2
Closes #59
=> ci: Add action for xtask codegen

aya/src/maps/mod.rs
While I was debugging #88, I noticed that generic map errors don't report the underlying `io_error` that caused the issue. Since the `bpf(2)` syscall always fails with -1 and sets errno, this effectively results in zero useful information being conveyed to the caller. This patch fixes `MapError` to report the io_error as the source, consistent with the way we already handle `ProgramError`.
=> aya/maps: improve map errors to be more descriptive

aya/Cargo.toml, aya/src/sys/netlink.rs
NETLINK_EXT_ACK is available since libc crate version 0.2.105, see
https://github.com/rust-lang/libc/releases/tag/0.2.105
=> aya: netlink: use NETLINK_EXT_ACK from libc crate

bpf/aya-bpf/src/helpers.rs
Until we add another set of bpf_probe_read_* wrappers for reading into a map pointer,
users need access to the underlying bpf_probe_read helper, which is clobbered by this
module. This patch enables direct access to the underlying helpers::gen module to support
such use cases.
In my view, it would also probably make sense to just not export helpers::gen::* and force
the user to opt into helpers::gen, but this can be decided on later.
Signed-off-by: William Findlay <william@williamfindlay.com>
=> aya-bpf/helpers: expose raw bindings through helpers::gen

bpf/aya-bpf/src/helpers.rs
This patch adds some documentation to aya-bpf/helpers and adds documentation
for the module itself and for all of the wrappers currently defined in the module.
It also implements the rest of the bpf_probe_read_* wrappers that were missing from this
file. In the future, it probably also makes sense to add some bpf_probe_read_* wrappers
that can read directly into a map pointer, avoiding the BPF stack altogether. I'm going to
call this out of scope for this PR, but plan to submit a subsequent one that addresses
this use case.
=> aya-bpf/helpers: add documentation and implement more bpf_probe_read_* wrappers

.github/workflows/gen.yml, xtask/src/codegen/aya.rs, xtask/src/codegen/aya_bpf_bindings.rs, xtask/src/codegen/mod.rs
This fixes binding generation for archs other than x86, and makes it possible to specify sysroot paths when running codegen on distros other than ubuntu.
=> Fix bindings for archs other than x86

bpf/aya-bpf-macros/Cargo.toml, bpf/aya-bpf/build.rs, bpf/aya-bpf/src/args.rs, bpf/aya-bpf/src/lib.rs, bpf/aya-bpf/src/programs/lsm.rs, bpf/aya-bpf/src/programs/probe.rs, bpf/aya-bpf/src/programs/tp_btf.rs
This PR introduces argument coercion for pt_regs and BTF program types and implements it for kprobes, uprobes, LSM programs, and BTF tracepoints.
You can see a [more concrete example of using this API here][1].
Features:
- Uses a FromBtfArgs trait with blanket implementations to enable coercion to both primitive types _and_ raw pointers
- No need for the user to perform any kind of manual casting on the BPF side
- Similar logic for pt_regs programs, abstracting over the PT_REGS access
TODO:
- Need to support architectures other than x86 for k/uprobe arguments (bindings need to be fixed)
While I was at it, I modified the Cargo.toml file of aya-bpf-macros to fix broken doctests. Perhaps we should add doctests to the CI workflow?
Closes #21
[1]: …
=> aya-bpf: introduce argument coercion

bpf/aya-bpf/src/maps/sock_hash.rs, bpf/aya-bpf/src/maps/sock_map.rs
This implements redirect_skb and renames redirect to redirect_msg
=> bpf: Implement redirect for skbs on sockmap/sockhash

aya/src/sys/bpf.rs, aya/src/sys/mod.rs
In kernel 4.15 and additional parameter was added to allow maps to have names but using this breaks on older kernels. This change makes it so the name is only added on kernels 4.15 and newer.
Symptoms of the problem would show up like
```
error: map error: failed to create map `IPV4_EVENTS` with code -1: Invalid argument (os error 22)`
```
and in `strace` output would look like
```
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_PERF_EVENT_ARRAY, key_size=4, value_size=4, max_entries=8, map_flags=0, inner_map_fd=0, map_name="IPV4_EVENTS", map_ifindex=0}, 128) = -1 EINVAL (Invalid argument)
```
After this patch the `strace` output looks like 
```
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_PERF_EVENT_ARRAY, key_size=4, value_size=4, max_entries=2, map_flags=0, inner_map_fd=0, map_name="", …
```
=> fix: make maps compatible with kernel <= 4.14

aya/src/programs/mod.rs
When a BPF program doesn't specify the target kernel version, the
most compatible option is to set the program kernel version to match
the currently running kernel.
=> Use current kernel version as default if not specified

bpf/aya-bpf-macros/src/expand.rs
This ensures the macro expands to the link section named `cgroup/skb` when no attach direction is provided.
Otherwise it uses `cgroup_skb/ingress` or `cgroup_skb/egress`.
I also added some tests, hopefully these can be added to check the output of other macros.
=> bpf: Fix cgroup_skb macro

aya/src/util.rs
This allows one to this macro with literal expressions involving macros
such as concat! and env!.
=> aya: expand include_bytes_aligned to accept expressions.

aya/src/maps/array/program_array.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/hash_map/per_cpu_hash_map.rs, aya/src/maps/mod.rs, aya/src/maps/sock/sock_hash.rs, aya/src/maps/stack_trace.rs, aya/src/programs/mod.rs, aya/src/util.rs
This should improve performance in most situations by eliminating
unnecessary fat pointer indirection.
=> aya: remove unnecessary usage of &dyn trait in favor of impl trait.

aya/src/bpf.rs, aya/src/maps/array/program_array.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/mod.rs, aya/src/maps/sock/sock_hash.rs, aya/src/maps/sock/sock_map.rs, aya/src/obj/mod.rs, aya/src/obj/relocation.rs, aya/src/programs/cgroup_skb.rs, aya/src/programs/kprobe.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/lsm.rs, aya/src/programs/mod.rs, aya/src/programs/perf_event.rs, aya/src/programs/raw_trace_point.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/sock_ops.rs, aya/src/programs/socket_filter.rs, aya/src/programs/tc.rs, aya/src/programs/tp_btf.rs, aya/src/programs/trace_point.rs, aya/src/programs/uprobe.rs, aya/src/programs/xdp.rs
Map and ProgramData objects had unnecessarily cloned strings for their
names, despite them being just as easily available to external users via
bpf.maps() and bpf.programs().
=> aya: eliminate name duplication in maps and programs.

aya/src/maps/array/array.rs, aya/src/maps/array/per_cpu_array.rs, aya/src/maps/array/program_array.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/hash_map/per_cpu_hash_map.rs, aya/src/maps/mod.rs, aya/src/maps/sock/sock_hash.rs, aya/src/maps/sock/sock_map.rs, aya/src/maps/stack_trace.rs
Map iteration can yield stale keys and values by virtue of sharing a
data structure with BPF programs which can modify it. However, all
accesses remain perfectly safe and will not cause memory corruption or
data races.
=> aya: Remove unnecessary unsafe markers on map iteration.

aya/src/obj/mod.rs
This commit improves section detection.
Previously, a section named "xdp_metadata" would be interpretted as a
program section, which is incorrect. This commit first attempts to
identify a BPF section by name, then by section.kind() ==
SectionKind::Text (executable code). The computed section kind is
stored in the Section so variants can be easily matched on later.
=> obj: Improve section detection

aya/src/bpf.rs
This is intended so that `Pod` could hold IPv6 addresses as well.
cc @dave-tucker @alessandrod PTAL.
=> Implement Pod for u128 and i128

.github/workflows/build-aya-bpf.yml
This ensures that the cache action uses the correct Rust version
=> github: Set toolchain override

aya/src/bpf.rs, aya/src/obj/mod.rs, aya/src/programs/fentry.rs, aya/src/programs/fexit.rs, aya/src/programs/lsm.rs, aya/src/programs/mod.rs, aya/src/programs/raw_trace_point.rs, aya/src/programs/tp_btf.rs, aya/src/programs/utils.rs, bpf/aya-bpf-macros/src/expand.rs, bpf/aya-bpf-macros/src/lib.rs, bpf/aya-bpf/src/programs/fentry.rs, bpf/aya-bpf/src/programs/fexit.rs, bpf/aya-bpf/src/programs/mod.rs
fentry and fexit programs are similar to kprobe and kretprobe, but they
are newer and they have practically zero overhead. Also, fexit programs
are focused on access to arguments rather than the return value.
Those kind of programs were introduced in the following patchset:
https://lwn.net/Articles/804112/
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
=> Support for fentry and fexit programs

aya/src/bpf.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/mod.rs, aya/src/maps/perf/perf_event_array.rs, aya/src/obj/mod.rs, aya/src/sys/bpf.rs, aya/src/util.rs
This commit marks .rodata maps as BPF_F_RDONLY_PROG when loaded to
prevent a BPF program mutating them.
Initial map data is populated by the loader using the new `BpfLoader::set_global()` API.
The loader will mark a map as frozen using bpf_map_freeze to prevent map data
being changed from userspace.
Related to #117
=> Mark .rodata maps as readonly and freeze on load

bpf/aya-bpf-macros/src/lib.rs
Doctests were broken due to depencencies on a generated vmlinux, incorrect function
signatures, and a missing unsafe keyword.
=> bpf/macros: fix tests

bpf/aya-bpf-macros/src/lib.rs, bpf/aya-bpf/src/args.rs, bpf/aya-bpf/src/helpers.rs
This helper allows to write to mutable pointers in the userspace, which
come from userspace functions that uprobes attach to.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
=> aya-bpf: Add bpf_probe_write_user helper

aya/src/sys/bpf.rs
the pointer isn't valid in the current code!
=> aya: allocate func/line_info buffers outside if

xtask/src/codegen/aya.rs
Add the `bpf_lpm_trie_key` to aya codegen to generate bindings.
cc: @alessandrod @dave-tucker
=> Add bpf_lpm_trie_key to bindings

xtask/src/codegen/aya.rs
This is required to add support for BTF_KIND_DECL_TAG
=> codegen: add btf_decl_tag

aya/src/programs/mod.rs
=> aya: Truncate long program names

aya/src/bpf.rs, aya/src/obj/btf/btf.rs, aya/src/obj/btf/types.rs, aya/src/sys/bpf.rs
This adds support for the BTF_TYPE_KIND_TAG and BTF_TYPE_KIND_DECL_TAG.
Along with the necessary feature probing and BTF sanitization.
=> btf: Add support for BTF_TYPE_KIND_{TAG,DECL_TAG}

aya/src/obj/btf/btf.rs
The lower 16 bits were not actually being cleared.
=> btf: fix sanitization if BTF_FUNC_GLOBAL is not supported

aya/src/bpf.rs, aya/src/obj/btf/btf.rs, aya/src/obj/btf/types.rs, aya/src/sys/bpf.rs
Aya will now perform sanitzation and fixups in a single phase, requiring
only one pass over the BTF. This modifies the parsed BTF in place.
=> aya: Merge Fixup and Sanitzation to single step

aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs
Adds support for map type `BPF_MAP_TYPE_LPM_TRIE`.
Fixes #128 
Some resources:
- https://www.ferrisellis.com/content/ebpf_syscall_and_maps/#bpf_map_type_lpm_trie
- https://blog.apnic.net/2020/10/23/journeying-into-xdp-augmenting-the-dns/
- https://www.lewuathe.com/longest-prefix-match-with-trie-tree.html
cc: @dave-tucker @alessandrod 
cc: @alessandrod @dave-tucker PTAL.
=> Add support for BPF_MAP_TYPE_LPM_TRIE

.github/workflows/build-aya-bpf.yml
This was testing the aya crate with the nightly toolchain which wasn't
what was intented
=> ci: Fix aya-bpf workflow

.github/workflows/lint.yml
=> ci: lint: aya: Skip doctests with miri

aya/src/bpf.rs
Use `static` instead of `const` and mention the necessity of using
`core::ptr::read_volatile`.
=> bpf: Improve documentation of set_global method

aya/src/bpf.rs
If a type is POD (meaning it can be converted to a byte array), then an array of such type is POD.
=> aya: implement Pod for arrays of Pod types

aya/src/bpf.rs, aya/src/obj/mod.rs
fa037a88e2f0820d2a64bbaae12464bf5dce083d allowed for cgroup skb programs
that did not specify an attach direction to use the cgroup/skb section
name per the convention established in libbpf. It did not add the
necessary code to load programs from those sections which is added in
this commit
Fixes: #225 
=> aya: Fix Loading from cgroup/skb sections

aya/src/obj/mod.rs
`BPF_PROG_TYPE_SOCKET_FILTER` program expands the sectionname's kind with `socket` not `socket_filter`.
So current eBPF program with socket filter always fails. (Please refer to  https://github.com/aya-rs/aya/issues/227.)
This patch fixes it.
Fix https://github.com/aya-rs/aya/issues/227
=> Fix socket_filter section match

bpf/aya-bpf/src/programs/sk_buff.rs
This change exposes the BPF helper bpf_socket_get_uid as a public method
of SkBuffContext, which allows to get the owner UID of the socket
associated to the sk_buff stored in the context.
=> bpf: sk_buff: Add get_socket_uid method to SkBuffContext

bpf/aya-bpf/src/programs/sk_msg.rs
This patch expose sk_msg_md of SkMsgContext, it is similar change with https://github.com/aya-rs/aya/pull/239.
=> aya-bpf: expose sk_msg_md of SkMsgContext

bpf/aya-bpf/src/programs/sock_ops.rs
This patch expose bpf_sock_ops of `SockOpsContext`.
=> aya-bpf: expose bpf_sock_ops of SockOpsContext

aya/src/maps/perf/perf_buffer.rs, aya/src/maps/perf/perf_event_array.rs
This changes PerfBuffer::read_events() to call BytesMut::reserve()
internally, and deprecates PerfBufferError::MoreSpaceNeeded.
This makes for a more ergonomic API, and allows for a more idiomatic
usage of BytesMut. For example consider:
let mut buffers = vec![BytesMut::with_capacity(N), ...];
loop {
let events = oob_cpu_buf.read_events(&mut buffers).unwrap();
for buf in &mut buffers[..events.read] {
let sub: Bytes = buf.split_off(n).into();
process_sub_buf(sub);
}
...
}
This is a common way to process perf bufs, where a sub buffer is split
off from the original buffer and then processed. In the next iteration
of the loop when it's time to read again, two things can happen:
- if processing of the sub buffer is complete and `sub` has been
dropped, read_events() will call …
=> aya: perf_buffer: call BytesMut::reserve() internally

bpf/aya-bpf/src/lib.rs
Add simplest possible memcpy that the verifier should never trip on
=> ebpf: add fallback memcpy

bpf/aya-bpf/src/helpers.rs
This patch fixes a tiny typo by removing unnecessary space in `aya_bpf:: helpers::bpf_get_current_comm`.
=> Fix tiny typo

aya/src/obj/mod.rs, test/README.md, test/cases/010_load/010_multiple_maps/multimap.bpf.c, test/cases/010_load/010_multiple_maps/multimap.rs, test/cases/010_load/010_multiple_maps/test.sh
This commit uses the symbol table to discover all maps inside an ELF
section. We then divide the data in to equal sized chunks and parse them
using parse_map_def
=> aya: Support multiple maps in map sections

aya-gen/src/bindgen.rs
It's a workaround for the upstream bindgen issue:
https://github.com/rust-lang/rust-bindgen/issues/2083
tl;dr: Rust nightly complains about #[repr(packed)] structs deriving
Debug without Copy.
It needs to be fixed properly upstream, but for now we have to disable
Debug derive here.
=> aya-gen: Disable Debug derive for BTF types

aya/Cargo.toml, aya/src/bpf.rs, aya/src/programs/cgroup_skb.rs, aya/src/programs/extension.rs, aya/src/programs/fentry.rs, aya/src/programs/fexit.rs, aya/src/programs/kprobe.rs, aya/src/programs/links.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/lsm.rs, aya/src/programs/mod.rs, aya/src/programs/perf_attach.rs, aya/src/programs/perf_event.rs, aya/src/programs/probe.rs, aya/src/programs/raw_trace_point.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/sock_ops.rs, aya/src/programs/socket_filter.rs, aya/src/programs/tc.rs, aya/src/programs/tp_btf.rs, aya/src/programs/trace_point.rs, aya/src/programs/uprobe.rs, aya/src/programs/utils.rs, aya/src/programs/xdp.rs, aya/src/sys/bpf.rs
Remove LinkRef and remove the Rc<RefCell<_>> that was used to store type-erased link values in ProgramData. Among other things, this allows `Bpf` to be `Send`, which makes it easier to use it with async runtimes.
Change the link API to:
let link_id = prog.attach(...)?;
...
prog.detach(link_id)?;
Link ids are strongly typed, so it's impossible to eg:
let link_id = uprobe.attach(...)?;
xdp.detach(link_id);
As it would result in a compile time error.
Links are still stored inside `ProgramData`, and unless detached explicitly, they are automatically detached when the parent program gets dropped.
=> aya: rework links

aya/src/bpf.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/obj/mod.rs, aya/src/obj/relocation.rs
Since we support multiple maps in the same section, the section_index is
no longer a unique way to identify maps. This commit uses the symbol
index as the identifier, but falls back to section_index for rodata
and bss maps since we don't retrieve the symbol_index during parsing.
=> aya: Relocate maps using symbol_index

bpf/aya-bpf/src/programs/sk_buff.rs
It is possible to access the skb pointer with as_ptr method of BpfContext, but direct access to skb is better, because as_ptr requires a cast.
Accessing skb is necessary to write missing functions or to access skb_buff properties such as ifindex, data, data_end, hash, etc
You can implement missing methods directly into SkBuffContext implementation, but in the future a new method may suddenly appear.
So I think that solution is good.
=> aya-bpf: Set skb_buff visbility to pub

xtask/src/codegen/aya_bpf_bindings.rs
This patch replaces `bpf_map_.*` with `bpf_.*`.
Currently some types that are not used in helper functions are not generated for bindings - e.g. `bpf_sk_lookup`, `bpf_sockopt` and etc.
Part of https://github.com/aya-rs/aya/issues/219
Note, this PR does not include bindings files as it would be better to be created by auto script.
The bindings can be updated by `cargo xtask codegen --libbpf-dir /<PATH_TO>/libbp`.
=> xtask: Add `bpf_.*` instead of `bpf_map_.*` to allowed type

aya/src/programs/cgroup_skb.rs
As per title, this patch sets `expected_attach_type` during load.
Fix https://github.com/aya-rs/aya/issues/262
=> Set attach type during load for BPF_PROG_TYPE_CGROUP_SKB

bpf/aya-bpf/src/helpers.rs
Before this change, documentation of helper functions (defined by us,
not bindings) were not visible, because `use gen::*` was overriding them
with helpers coming from aya-bpf-bindings, which have the same names and
no docs.
=> bpf(doc): Hide docs of bindings

aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/cgroup_sysctl.rs, aya/src/programs/extension.rs, aya/src/programs/fentry.rs, aya/src/programs/fexit.rs, aya/src/programs/links.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/mod.rs, aya/src/programs/perf_attach.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/sock_ops.rs, aya/src/programs/socket_filter.rs, aya/src/programs/trace_point.rs, aya/src/programs/xdp.rs
This allows access to XdpLink, XdpLinkId etc... which is currently
unavailable since these modules are private
=> aya: Export program modules

bpf/aya-bpf/src/args.rs, bpf/aya-bpf/src/lib.rs
This adds a portable wrapper around pt_regs and user_pt_regs.
It makes writing Raw Tracepoint or KProbe programs easier when the
arguments are one of these types while also ensuring code is portable
across architectures.
Updates: #207
=> bpf: Add PtRegs wrapper

bpf/aya-bpf/src/maps/mod.rs, bpf/aya-bpf/src/maps/stack.rs
Currently BPF_MAP_TYPE_STACK is supported by user code (`aya/src/maps/stack.rs`),
but it does not support the `BPF_MAP_TYPE_STACK` in BPF code.
This patch fixes it.
=> Add missing BPF_MAP_TYPE_STACK in BPF code

aya/src/maps/bloom_filter.rs, aya/src/maps/mod.rs, aya/src/maps/stack_trace.rs, aya/src/sys/bpf.rs, bpf/aya-bpf/src/maps/bloom_filter.rs, bpf/aya-bpf/src/maps/mod.rs
This patch adds support for `BPF_MAP_TYPE_BLOOM_FILTER`.
Close https://github.com/aya-rs/aya/issues/204
=> Add support for BPF_MAP_TYPE_BLOOM_FILTER

xtask/src/docs/mod.rs
=> Revert "docs: Merge search indexes"

aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/cgroup_sysctl.rs, aya/src/programs/extension.rs, aya/src/programs/fentry.rs, aya/src/programs/fexit.rs, aya/src/programs/kprobe.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/lsm.rs, aya/src/programs/mod.rs, aya/src/programs/perf_event.rs, aya/src/programs/raw_trace_point.rs, aya/src/programs/sk_lookup.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/sock_ops.rs, aya/src/programs/socket_filter.rs, aya/src/programs/tc.rs, aya/src/programs/tp_btf.rs, aya/src/programs/trace_point.rs, aya/src/programs/uprobe.rs, aya/src/programs/xdp.rs, test/cases/010_load/030_unload/test.rs
=> aya: Rename forget_link to take_link

bpf/aya-bpf/src/programs/sock_ops.rs
Allow getting family, remote/local v4/v6 addresses and the remote and
local ports.
=> bpf: Add accessors to SockOpsContext

bpf/aya-bpf/src/maps/array.rs, bpf/aya-bpf/src/maps/hash_map.rs, bpf/aya-bpf/src/maps/lpm_trie.rs, bpf/aya-bpf/src/maps/per_cpu_array.rs, bpf/aya-bpf/src/maps/perf/perf_event_array.rs, bpf/aya-bpf/src/maps/perf/perf_event_byte_array.rs, bpf/aya-bpf/src/maps/program_array.rs, bpf/aya-bpf/src/maps/queue.rs, bpf/aya-bpf/src/maps/sock_hash.rs, bpf/aya-bpf/src/maps/sock_map.rs, bpf/aya-bpf/src/maps/stack_trace.rs, test/cases/020_elf/000_maps/map_test.ebpf.rs
The bpf_map_defs are now wrapped with UnsafeCell, which also happens to
provide a cozy way to get a *mut pointer. An UnsafeCell isn't strictly
required as the struct fields are practically opaque to us, but using an
UnsafeCell follows the general best practices against miscompilation and
also prevents some obvious errors.
HashMap::get_mut was removed because the idea is completely unsound.
Previous users should wrap their data with UnsafeCell instead or use
atomics.
Closes: #233
=> bpf: Replace map types to use &self, remove HashMap::get_mut

bpf/aya-bpf/src/maps/per_cpu_array.rs
=> bpf: Remove unnecessary Sync bound on PerCpuArray<T>

.github/workflows/build-aya-bpf.yml, .github/workflows/build-aya.yml, bpf/aya-bpf/src/args.rs
As it turns out, the verifier gets upset if you try to read the values
directly without using bpf_probe_read.
=> bpf: bpf_probe_read_kernel fields in pt_regs

aya-gen/src/bin/aya-gen.rs, xtask/src/codegen/mod.rs, xtask/src/docs/mod.rs
Fixes [linting errors](https://github.com/aya-rs/aya/runs/6871782093?check_suite_focus=true) on `main`
A good part of those were caused by [clap changes in 3.2](https://epage.github.io/blog/2022/06/clap-32-last-call-before-40/)
=> Fix linting issues

aya/src/maps/mod.rs
A rework of #322 to not accomplish the same thing without a trait... in a similar way to how #282 does with `ProgramFd`
=> aya: Add Map::fd() function to return a MapFd

bpf/aya-bpf/src/programs/xdp.rs
I think these inline attributes are missing for XdpContext.
=> Add missing inline macro to xdp methods

aya/src/maps/array/program_array.rs, aya/src/programs/extension.rs, aya/src/programs/mod.rs, aya/src/programs/xdp.rs, aya/src/sys/bpf.rs
This PR adds:
- `bpf_link_update`
- `Xdp::attach_to_link` - which allows for atomic replacement of XDP programs
- `Extension::attach_to_program` - which allows for an Extension program to be attached to a program other than the one provided at `load()` - which is required as the verifier needs to know where it will be attached. The program/function should be BTF compatible or the call will fail.
These changes are collected together to enable the following use case in `bpfd`
1. Attach an `Xdp` [dispatcher program ](https://github.com/xdp-project/xdp-tools/blob/master/lib/libxdp/protocol.org) to an interface with an `Xdp` program loaded as an `Extension` to `func1`.
1. A user requests that a new Xdp extension be loaded at `func2`
1. Create a new `Xdp` dispatcher program.
1. Attach the …
=> Add atomic replacement of XDP progs and multihoming of Extension progs

aya/src/maps/array/array.rs, aya/src/maps/array/program_array.rs, aya/src/maps/hash_map/mod.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/perf/perf_event_array.rs, aya/src/maps/sock/sock_map.rs, aya/src/maps/stack.rs, aya/src/sys/bpf.rs
bpf_map_update_elem is used in lieu of bpf_map_push_elem to maintain support for kernel version < 4.20. The kernel expects a null pointer for the key for this use case. With this change, if you pass None as key to `bpf_map_update_elem`, it will pass null as key.
=> Have bpf_map_update_elem take Option<&K> for key

aya/src/maps/mod.rs, aya/src/programs/mod.rs
Also, mention that setting the RLIMIT_MEMLOCK to a higher value is an
option.
=> aya: Raise the RLIMIT_MEMLOCK warning only if failed to create a map

bpf/aya-bpf/src/maps/bloom_filter.rs, bpf/aya-bpf/src/maps/hash_map.rs, bpf/aya-bpf/src/maps/lpm_trie.rs, bpf/aya-bpf/src/maps/queue.rs, bpf/aya-bpf/src/maps/sock_hash.rs, bpf/aya-bpf/src/maps/sock_map.rs, bpf/aya-bpf/src/maps/stack.rs
This change fixes the `unnecessary_lazy_evaluations` clippy warning.
=> bpf: Use `then_some` instead of `then(|| [...])`

aya/src/bpf.rs, aya/src/maps/array/array.rs, aya/src/maps/array/per_cpu_array.rs, aya/src/maps/array/program_array.rs, aya/src/maps/bloom_filter.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/hash_map/mod.rs, aya/src/maps/hash_map/per_cpu_hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/maps/perf/perf_event_array.rs, aya/src/maps/queue.rs, aya/src/maps/sock/sock_hash.rs, aya/src/maps/sock/sock_map.rs, aya/src/maps/stack.rs, aya/src/maps/stack_trace.rs, aya/src/obj/mod.rs, aya/src/obj/relocation.rs, aya/src/sys/bpf.rs, test/integration-ebpf/src/bpf/multimap-btf.bpf.c, test/integration-test/src/tests/load.rs
This PR allows for BTF maps in the .maps ELF section to be parsed.
It reads the necessary information from the BTF section of the ELF file.
It provides the BTF IDs to the `bpf_map_create` call.
This allows for `bpftool` to pretty print maps! For example:
```bash
$ sudo bpftool map dump id 224 
[{
"key": 0,
"value": {
"rx_packets": 0
}
},{
"key": 1,
"value": {
"rx_packets": 0
}
},{
"key": 2,
"value": {
"rx_packets": 148
}
},{
"key": 3,
"value": {
"rx_packets": 0
}
},{
"key": 4,
"value": {
"rx_packets": 0
}
}
]
```
=> Support Parsing of BTF Maps

bpf/aya-bpf/src/helpers.rs, bpf/aya-bpf/src/lib.rs
Change it from `[i8; 16]` to `[u8; 18]`. `i8` arrays cannot be easily used in
Rust for converting to string (i.e. with `core::str::from_utf8_unchecked`)
and developers have to convert them themselves with unsafe code.
Using u8 arrays lets developers to just convert it with
`core::str::from_utf8_unchecked` without any limitations.
Example:
https://github.com/vadorovsky/aya-examples/blob/main/clone/clone-ebpf/src/main.rs
=> bpf: Change the result type of bpf_get_current_comm helper

bpf/aya-bpf/src/helpers.rs
The `bpf_printk!` macro is a helper providing a convenient way to invoke the `bpf_trace_printk` and `bpf_trace_vprintk` BPF helpers. It is implemented as a macro because it requires variadic arguments.
=> bpf: add `bpf_printk!` helper

aya-log-common/src/lib.rs, aya-log/src/lib.rs
They are not supported by eBPF VM and we are going to use arrays for
IPv6.
=> aya-log: Remove i128 and u128 types

aya/src/bpf.rs, aya/src/lib.rs, aya/src/maps/mod.rs, aya/src/pin.rs, aya/src/programs/links.rs, aya/src/programs/mod.rs
1, Allow pinning from the program directly (e.g `TracePoint::pin("/path")`
2. Add `FdLink::pin("/path")`, which requires that you've called `take_link()` first, which actually isn't a bad thing at all :wink:
=> Small Pinning API improvements

aya/src/maps/mod.rs
=> aya: Remove MapError::InvalidPinPath

bpf/aya-bpf/src/maps/lpm_trie.rs
Hi, this is a very minor fix to the docs of `lpm_trie::Key` I think the `prefix_len` represent the number of bits instead of the number of bytes to match against, this is needed to work with the whole range of CIDRs
=> Minor fix for `lpm_trie::key` docs

aya-log/README.md
The aya-log repo ([0]) has been archived, use the link to
aya repo instead.
Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>
=> aya-log/README: Fix links to aya-log repo

bpf/aya-bpf/src/maps/lpm_trie.rs
The Linux kernel requires BPF_F_NO_PREALLOC on creating LPMTrie ([0]).
Add BPF_F_NO_PREALLOC flag in LPMTrie constructor.
Closes #332.
[0]: https://github.com/torvalds/linux/blob/9e6b19a66d9b/kernel/bpf/lpm_trie.c#L551
Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>
=> aya-bpf/maps: Create LPMTrie with BPF_F_NO_PREALLOC

Cargo.toml, aya-log-common/Cargo.toml, aya-log-common/src/lib.rs, aya-log-ebpf-macros/Cargo.toml, aya-log-ebpf-macros/src/expand.rs, aya-log-parser/Cargo.toml, aya-log-parser/src/lib.rs, aya-log/Cargo.toml, aya-log/src/lib.rs, bpf/aya-log-ebpf/src/lib.rs
This change adds optional display hints:
* `{:x}`, `{:X}` - for hex representation of numbers
* `{:ipv4}`, `{:IPv4}` - for IPv4 addresses
* `{:ipv6}`, `{:IPv6}` - for IPv6 addresses
It also gets rid of dyn-fmt and instead comes with our own parser
implementation.
Tested on: https://github.com/vadorovsky/aya-examples/tree/main/tc
=> lib: Add display hints

aya-log-ebpf-macros/src/expand.rs
=> aya-log-ebpf-macros: Fix the DisplayHint expression names

aya/src/obj/btf/btf.rs, aya/src/obj/btf/relocation.rs, aya/src/obj/btf/types.rs, aya/src/obj/mod.rs, aya/src/sys/bpf.rs
This commit removes reliance on generated BtfType structs, as
well as adding a dedicated struct for each BTF type. As such,
we can now add nice accessors like `bits()` and `encoding()`
for Int vs. inlined shift/mask operations.
=> aya: Improved BTF Type API

aya/src/programs/links.rs, test/integration-test/src/tests/load.rs
The From<$wrapper> for $base implemention is refers to itself,
eventually causing a segfault.
=> aya: Fix segfault in define_link_wrapper

aya/src/bpf.rs
As talked with @alessandrod [here](https://discord.com/channels/855676609003651072/855676609003651075/1014213239762067486), using `bitflags!` to implement the `VerifierLogLevel`.
I think that using the `Default` trait might be better than having a `DEFAULT` value in the struct but not so sure on that.
Also setting `Level2` as `Level1 | 2` since in the kernel level 1 seems to imply level 2. Meaning, that when they check for log level they either check for [`BPF_LOG_LEVEL2`](https://github.com/torvalds/linux/blob/f16214c102f0f64b2f3546e989498525bd7b7708/include/linux/bpf_verifier.h#L419) (when it's exclusive to 2) or [`BPF_LOG_LEVEL`](https://github.com/torvalds/linux/blob/f16214c102f0f64b2f3546e989498525bd7b7708/include/linux/bpf_verifier.h#L422) when it also include level 1, So I didn't …
=> Update `VerifierLogLevel` to use bitflags

aya-tool/src/generate.rs, aya/src/programs/extension.rs, aya/src/programs/links.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/mod.rs, aya/src/programs/xdp.rs, aya/src/sys/bpf.rs, test/integration-test/src/tests/load.rs
This PR adds some missing lifecycle APIs required for working with pins.
1. Adds PinnedLink::from_path to create a pinned link from bpffs
1. Adds From<PinnedLink> for FdLink to allow for ^ to be converted
1. Adds TryFrom<FdLink> for XdpLink
=> aya: More pinning fixes

aya/src/bpf.rs, aya/src/maps/array/array.rs, aya/src/maps/array/per_cpu_array.rs, aya/src/maps/array/program_array.rs, aya/src/maps/bloom_filter.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/hash_map/mod.rs, aya/src/maps/hash_map/per_cpu_hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/maps/queue.rs, aya/src/maps/sock/sock_hash.rs, aya/src/maps/sock/sock_map.rs, aya/src/maps/stack.rs, aya/src/maps/stack_trace.rs, aya/src/obj/mod.rs, aya/src/programs/extension.rs, aya/src/sys/bpf.rs
fixes #385 
This PR adds the new `aya::maps::{from_pinned, from_fd}` APIs. Which will allow users to load in and interact with BPF maps from either a raw file descriptor or map pin point. 
The user can get a concrete aya map type to interact with like so 
```rust
let map_pin_path = Path::new("/sys/fs/bpf/basic-node-firewall/BLOCKLIST");
let mut block_map = Map::from_pinned(map_pin_path)?; 
let mut blocklist: HashMap<_, PacketFiveTuple, u32> =
HashMap::try_from(&mut block_map)?;
```
I tested this locally with a pinned map, but was unsure exactly how to add unit tests....and would appreciate any feedback on that :)
=> Load static maps

aya/src/maps/mod.rs, aya/src/programs/links.rs, aya/src/programs/mod.rs, test/integration-test/src/tests/load.rs
As discussed in #387, we should settle on one name for these APIs.
`from_pinned` - stutters when used with a type like `PinnedLink`
`from_path` - implies that any path could be used.
`from_pin` - seems like the best compromise.
=> Consistently name Pin APIs as from_pin

aya/src/bpf.rs
Fixes the issue #308.
Add BpfLoader::set_max_entries so that the max_entries of any map on the ebpf component
can be set at the load-time on the userspace component.
The max_entries of the map that matches the map name given in the first argument is overwritten
by the value of the second argument.
Fixes: #308
Refs: #292
=> aya: add BpfLoader::set_max_entries

aya/Cargo.toml, aya/src/lib.rs, aya/src/maps/perf/async_perf_event_array.rs, aya/src/maps/perf/mod.rs, aya/src/programs/links.rs, xtask/src/docs/mod.rs
Following the lead of crates like tokio and nix, we now annotate APIs that require optional features. This helps in cases where a user wants to have an `AsyncPerfEventArray` which is documented on crates.io, but it's not obvious that you have to enable the `async` feature.
=> docs: Add labels for optional features

CONTRIBUTING.md
PR adds a link to test/README.md / "Aya Integration Tests" section.
=> add doc pointer on integration tests in contributor guide

xtask/src/codegen/aya.rs, xtask/src/codegen/aya_bpf_bindings.rs
Fix the clippy warning on needless_borrow https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow which leads to the red CI lint builds.
=> fix clippy needless_borrow warnings

aya/src/maps/mod.rs
The syscall name is `BPF_OBJ_PIN`, not `BPF_OBJ_GET`.
=> maps: Fix the error message in `MapData::pin()`

aya-log-common/src/lib.rs, aya-log-ebpf-macros/src/expand.rs, aya-log-parser/src/lib.rs, aya-log/src/lib.rs
Add `{:mac}` (for lower-case hex representation) and `{:MAC}` (for upper-case hex representation) format hints for the `[u8; 6]` type, which is the standard one in Linux to store physical addresses in.
Tested with: https://github.com/vadorovsky/aya-examples/tree/main/xdp-mac
=> aya-log: Add format hints for MAC addresses

aya/src/maps/array/array.rs, aya/src/maps/bloom_filter.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/hash_map/mod.rs, aya/src/maps/hash_map/per_cpu_hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/queue.rs, aya/src/maps/sock/sock_hash.rs, aya/src/maps/stack.rs, aya/src/sys/bpf.rs, bpf/aya-bpf/src/maps/sock_hash.rs
This PR changes map related APIs to use reference to Pod instead of Pod. This should fix #427
=> aya: use impl Borrow<T> instead of T for maps

.gitignore, aya/src/programs/tc.rs, aya/src/sys/netlink.rs
Implements step 1 of https://github.com/aya-rs/aya/issues/414.
- Adds `handle` to the `SchedClassifier` `attach` API
- Saves `handle` in the `TcLink` sruct and uses it when detaching programs
NOTE: This pr changes the API, so I think it will require a bump in the Aya version.
Signed-off-by: Andre Fredette <afredette@redhat.com>
=> Support using handle in tc programs

.github/workflows/build-aya.yml, aya/src/obj/btf/relocation.rs
`'local` lifetime can be elided to `'_` which triggers:
https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
=> Fix clippy error

aya-bpf-macros/src/expand.rs, aya-log-ebpf-macros/src/expand.rs, aya-log-parser/src/lib.rs, aya-log/src/lib.rs, aya-tool/Cargo.toml, aya-tool/src/bin/aya-tool.rs, aya/src/obj/btf/btf.rs, aya/src/obj/btf/relocation.rs, aya/src/obj/btf/types.rs, aya/src/programs/lsm.rs, aya/src/programs/probe.rs, aya/src/programs/tp_btf.rs, aya/src/programs/trace_point.rs, aya/src/programs/uprobe.rs, aya/src/util.rs, bpf/aya-bpf-bindings/build.rs, bpf/aya-bpf-cty/build.rs, bpf/aya-bpf/build.rs, test/integration-test/Cargo.toml, xtask/Cargo.toml, xtask/src/build_ebpf.rs, xtask/src/build_test.rs, xtask/src/codegen/aya.rs, xtask/src/codegen/aya_bpf_bindings.rs, xtask/src/codegen/mod.rs, xtask/src/main.rs, xtask/src/run.rs
PR contains the results of applying `cargo +nightly clippy --fix` to fix
clippy's uninlined_format_args issues https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args.
Cumulative with https://github.com/aya-rs/aya/pull/454
=> autofix clippy uninlined_format_args issues

aya-bpf-macros/src/expand.rs, aya-bpf-macros/src/lib.rs, aya/src/bpf.rs, aya/src/obj/mod.rs, aya/src/programs/cgroup_device.rs, aya/src/programs/mod.rs, bpf/aya-bpf/src/programs/device.rs, bpf/aya-bpf/src/programs/mod.rs
Kernel 4.15 added a new eBPF program that can be used with cgroup v2 to control & observe device access (e.g. read, write, mknod) - `BPF_PROG_TYPE_CGROUP_DEVICE`.
We add the ability to create these programs with the `cgroup_device` proc macro which creates the `cgroup/dev` link section. Device details are available to the eBPF program in `DeviceContext`.
The userspace representation is provided with the `CgroupDevice` structure.
An example use this eBPF program can be seen here: [aya-cgroup-dev-example](https://github.com/bpfdeploy-io/aya-cgroup-dev-example/blob/main/cgroup-dev-ebpf/src/main.rs)
Fixes: #212
Signed-off-by: Milan <milan@mdaverde.com>
=> Add support for BPF_PROG_TYPE_CGROUP_DEVICE

aya/src/maps/lpm_trie.rs
I've done basic testing for `LpmTrie::iter()` and `LpmTrie::keys()` but have not tested `LpmTrie::iter_key()`.
This pull requests does not have any unit tests.
=> Add ability to iterate over LpmTrie keys and matches

aya/src/programs/cgroup_device.rs, aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/cgroup_sysctl.rs, aya/src/programs/extension.rs, aya/src/programs/links.rs, aya/src/programs/sk_lookup.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/sock_ops.rs, aya/src/programs/tc.rs, aya/src/programs/xdp.rs, test/integration-ebpf/src/test.rs, test/integration-test/src/tests/load.rs
https://github.com/aya-rs/aya/pull/366 broke detaching links on drop for everything but FdLink. This restores detach on drop for all links.
=> aya: fix detaching links on drop

bpf/aya-bpf/src/programs/sk_buff.rs
Such an assignment in two parts (first deref in `unsafe`, then field access outside of `unsafe`) is bogus: the deref "returned" by the `unsafe` block actually creates a copy of the `__sk_buff` struct because it implements `Copy`. The mark value is written to the `mark` field of the copy, and not the real `__sk_buff`.
Change it to do it all in the `unsafe` block.
The same is done for the `.len()` getter to avoid copying the whole `__sk_buff` struct for a 32 bit field. Although such a copy should be optimized out by the compiler, it's better to help it do so.
=> bpf: fix `set_mark` by not copying `__sk_buff`

aya/src/obj/btf/mod.rs, aya/src/obj/btf/relocation.rs
Error out instead of panicing when we can't find a compatible target candidate for a BTF relocation.
This can commonly happen if the loader is configured to not load BTF at all, or if the loaded BTF is older than the one used to generate the object file, so it doesn't have some newer type definitions.
=> Don't panic on failed BTF relocations

.github/workflows/build-aya.yml, test/integration-test/Cargo.toml, test/integration-test/src/main.rs, test/integration-test/src/tests/mod.rs, test/integration-test/src/tests/relocations.rs, test/run.sh, xtask/src/build_ebpf.rs
I've started to work on https://github.com/aya-rs/aya/issues/412
It's not ready for review yet, but I need some feedback before going on.
For now, I have a test for a moved field inside a struct and an enum change. The integration test works by trying to read a relocatable field from a raw array of bytes. The read data is then sent to userspace using a BPF_MAP_TYPE_ARRAY. The integration_test then asserts the output is consistent with the target BTF instead of the local definition.
Originally I was planning to send the relocatable data structure from userspace into eBPF using a global variable. I discarded that option because I felt it was making things more complicated and harder to understand than just reading the raw bytes.
I thought it would be best to have a test generator …
=> Add integration tests for BTF relocations

aya-obj/src/maps.rs
Include all new map types which were included in the last libbpf update (5d13fd5acaa9).
Fixes: cb28533e2f9e ("aya-obj: Update `BPF_MAP_TYPE_CGROUP_STORAGE` name to `BPF_MAP_TYPE_CGRP_STORAGE`")
=> aya-obj: Add new map types

test/integration-test/src/tests/smoke.rs
Before this chane, the check was always negative if the minor version was less then 9. So, for example, the smoke test was skipped for kernel 6.1:
```
skipping as 6.1 does not meet version requirement of 5.9
```
=> integration-test: Fix the kernel version chceck for smoke test

test/integration-test/src/tests/relocations.rs, test/run.sh, xtask/src/build_ebpf.rs
Simplifiy the relocation tests build process by removing the need for libbpf at runtime.
Its usage is replaced with local `__builtin_*` attributes.
This removes the need for the `LIBBPF_INCLUDE` env variable.
An alternative solution would be to create a `libbpf_polyfill.h` file with the needed definitions (and explain why the file is needed) and include just that from the relocation tests. Let me know if you'd prefer it that way.
=> Remove libbpf dependency from relocation tests

.github/workflows/build-aya-bpf.yml, .github/workflows/build-aya.yml, aya-obj/src/btf/types.rs, aya-obj/src/maps.rs, aya-obj/src/obj.rs, aya-obj/src/programs/cgroup_sock.rs, netlify.toml, xtask/src/build_ebpf.rs, xtask/src/docs/mod.rs
This until https://github.com/rust-lang/rust/pull/106796 gets fixed
=> Pin nightly to nightly-2023-01-10

aya/src/bpf.rs
Currently aya will just report a standard outer level error on failure.  Ensure that we also report the inner error condition back to the user
Currently: 
```
[2023-01-19T15:53:14Z WARN  bpfd::rpc] BPFD load error: map error
```
With Patch: 
```
[2023-01-19T17:36:10Z WARN  bpfd::rpc] BPFD load error: map error: failed to create map `ingress_node_firewall_events_map` with code -1
```
=> Expose inner errors

aya/src/programs/mod.rs, aya/src/programs/probe.rs, aya/src/programs/trace_point.rs, aya/src/programs/utils.rs
This PR would to improve the access to `tracefs`.
This is implemented with a single check to determine if the `tracefs` is mounted or not. It checks in two known locations, in order of priority:
1. `/sys/kernel/tracing`
2. `/sys/kernel/debug/tracing`
Most of the systems have both `tracefs` and `debugfs` mounted, but in some hardened systems the kernel is compiled without `debugfs` or simply not mounted. Android documentation for example has a warning for debugfs in user builds.
=> add tracefs mount point select function

aya-bpf-macros/src/expand.rs
Allow to define programs as public functions (even in library crates) and then import them.
For example, we can have library crate with `libfoo/src/lib.rs` containing:
```rust
#[xdp]
pub fn my_xdp_program(ctx: XdpContext) -> u32 {
xdp_action::XDP_PASS
}
```
And then a binary importing it:
```rust
pub use libfoo::my_xdp_program;
```
This way, commonly used eBPF programs can be distributed as lib crates.
Tested with: https://github.com/vadorovsky/aya-examples/tree/main/pub-progs
=> aya-bpf-macros: Allow to make programs public

.cargo/config, .github/workflows/build-aya.yml, .github/workflows/integration-tests.yml, test/cloud-localds, test/run.sh, xtask/src/build_test.rs
This PR changes integration tests to run under macos-latest, which is the only runner that supports nested virtualization. It also caches the qemu image we use for the virtual machine so that system dependencies installed with dnf and bpf-linker aren't rebuilt every time.
=> Speed up integration tests

aya-obj/src/btf/btf.rs, aya-obj/src/btf/relocation.rs, aya-obj/src/btf/types.rs, test/integration-test/src/tests/relocations.rs
Once upon a time relocations were always signed. That was changed and now enums include a sign bit in the info flags. Adjust the code accordingly.
=> aya: btf: fix relocations for signed enums (32 bits)

aya-obj/src/btf/relocation.rs, aya-obj/src/btf/types.rs, test/integration-test/src/tests/relocations.rs
This adds support for parsing and relocating `BTF_KIND_ENUM64` types.
=> Add support for BTF_KIND_ENUM64

aya/src/bpf.rs, aya/src/maps/mod.rs
They were broken by https://github.com/aya-rs/aya/pull/397
=> aya: fix Lru and LruPerCpu hash maps

aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/kprobe.rs, aya/src/programs/links.rs, aya/src/programs/lsm.rs, aya/src/programs/mod.rs, aya/src/programs/perf_event.rs, aya/src/programs/sk_skb.rs, aya/src/programs/tc.rs, aya/src/programs/tp_btf.rs, aya/src/programs/uprobe.rs, test/integration-test/src/tests/load.rs
This commit adds from_pin() which allows the creation of a Program from a path on bpffs. This is useful to be able to call `attach` or other APIs for programs that are already loaded to the kernel.
This differs from #444 since it implements this on the concrete program type, not the Program enum, allowing the user to pass in any additional context that isn't available from bpf_prog_info.
=> aya: Add from_pin for Programs

aya-tool/Cargo.toml, aya-tool/src/bindgen.rs
The comment says that `.derive_debug` was needed as a workaround for https://github.com/rust-lang/rust-bindgen/issues/2083. This issue is now closed, and aya-tool compiles without derive_debug.
Additionally, update bindgen dependency to 1.64.
Signed-off-by: Dmitry Savintsev <dsavints@gmail.com>
=> aya-tool: remove outdated workaround

aya-bpf-macros/src/expand.rs, aya-obj/src/obj.rs, aya/src/bpf.rs, aya/src/programs/mod.rs, aya/src/sys/bpf.rs, test/integration-ebpf/src/map_test.rs, test/integration-ebpf/src/pass.rs
=> XDP Multi-Buffer Support

aya-obj/src/btf/btf.rs, aya/src/bpf.rs, aya/src/programs/kprobe.rs, aya/src/programs/perf_attach.rs, aya/src/programs/perf_event.rs, aya/src/programs/probe.rs, aya/src/programs/trace_point.rs, aya/src/programs/uprobe.rs, aya/src/sys/bpf.rs
This adds support for using bpf_link to perf_attach programs.
In addition, it also makes the feature detection a lazy-static, which while not strictly necessary should allow applications to do feature detection only once when using Aya vs. every time a `Bpf` object is created.
This also allows for features to be used in other parts of the codebase that might require feature discovery to have happened already - I think I ran into this in the USDT probe PR which is why I implemented this in the first place!
=> Use bpf_link for perf_attach programs (Kprobe/Uprobe/Tracepoint etc...)

aya/src/sys/bpf.rs
This was mistakenly comparing the exit code of the syscall, which is always -1 and not the corresponding error-code. Added unit tests to ensure we don't regress.
=> aya: Fix is_perf_link_supported

aya/src/lib.rs, aya/src/programs/mod.rs, aya/src/sys/bpf.rs
This uses a Programs iterator to yield all loaded bpf programs using bpf_prog_get_next_id.
Example program [here](https://github.com/dave-tucker/prog-lister)
=> aya: Add loaded_programs() API to list all loaded programs

xtask/src/codegen/aya.rs
This PR adds bindings for the two userspace structs `bpf_cpumap_val` and `bpf_devmap_val`. It will be needed by #527 for full support of chained programs in cpu/devmap.
Also, it will need a bors run after merge to actually generate the bindings.
Thanks!
=> xtask: generate userspace bindings for bpf_{cpu,dev}map_val

aya/src/maps/mod.rs
The Clone implementation of MapData was previously not storing the result of the dup operation.
=> aya: Fix MapData Clone implementation

test/run.sh
Now that bpf-linker uses llvm 16, the easiest way is to use Fedora 38 Beta with the testing repos as they have it, without resorting to Rawhide.
See https://packages.fedoraproject.org/pkgs/llvm/llvm/.
=> tests: use fedora 38 beta with testing repo

Cargo.toml, test/integration-test/src/tests/elf.rs, test/integration-test/src/tests/load.rs, test/integration-test/src/tests/rbpf.rs, test/integration-test/src/tests/smoke.rs, xtask/src/build_ebpf.rs, xtask/src/run.rs
Also, add the `codegen-unit` option to the profile.
=> integration-tests: Build eBPF programs always with release profile

aya/src/sys/bpf.rs
Fixes a crash when trying to create a map of type `BPF_MAP_TYPE_PERCPU_ARRAY` when `btf_fd` is `None`.
Tested on Ubuntu 18.04 (4.15.0-202-generic)
=> aya: Do not use unwrap with btf_fd in bpf_create_map

aya-obj/src/obj.rs, aya/src/bpf.rs, aya/src/sys/bpf.rs
Required for kernel before 5.5.
=> aya: Add sanitize code for kernels without bpf_probe_read_kernel

aya/src/maps/array/array.rs, aya/src/maps/array/per_cpu_array.rs, aya/src/maps/array/program_array.rs, aya/src/maps/bloom_filter.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/hash_map/per_cpu_hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/maps/perf/async_perf_event_array.rs, aya/src/maps/perf/perf_event_array.rs, aya/src/maps/queue.rs, aya/src/maps/sock/sock_hash.rs, aya/src/maps/sock/sock_map.rs, aya/src/maps/stack.rs, aya/src/maps/stack_trace.rs
We don't ever do ref-to-ref conversion for MapData so Borrow should suffice.
=> aya: MapData should be Borrow, not AsRef

bpf/aya-bpf/src/programs/sk_buff.rs, bpf/aya-bpf/src/programs/tc.rs
This patch adds a new helper function, `change_proto`, to the `SkBuff` struct in the `aya-bpf` crate.
The `change_proto` function allows changing the protocol of a socket buffer (`skb`) in BPF programs.
This patch also adds a corresponding wrapper for the `change_proto` function in the `TcContext` struct in the `aya-bpf` crate, making it accessible from TC (traffic control) programs as well.
=> aya-bpf: Add helper `change_proto`

.github/workflows/build-aya.yml, aya-obj/Cargo.toml, aya-obj/src/btf/btf.rs, aya-obj/src/btf/relocation.rs, aya-obj/src/lib.rs, aya-obj/src/maps.rs, aya-obj/src/obj.rs, aya-obj/src/programs/cgroup_sock.rs, aya-obj/src/programs/cgroup_sock_addr.rs, aya-obj/src/programs/cgroup_sockopt.rs, aya-obj/src/relocation.rs, aya-obj/src/util.rs, aya/Cargo.toml
See the commit message for some useful words.
/cc @ajwerner
=> aya: flip feature "no_std" to feature "std"

aya-bpf-macros/src/expand.rs, aya-obj/src/obj.rs, aya/src/bpf.rs
This adds support for the `BPF_F_SLEEPABLE` flag for LSM : https://lore.kernel.org/netdev/20200827220114.69225-3-alexei.starovoitov@gmail.com/
It follows the same tack as XDP multi-buffer support: https://github.com/aya-rs/aya/pull/519
Internally, this option follows the `libbpf` convention and is represented as `lsm.s`: https://elixir.bootlin.com/linux/latest/source/tools/lib/bpf/libbpf.c#L8560
In the public API, this is exposed via the eBPF `lsm` macro as an optional `sleepable = "bool"` argument.
```
#[lsm(name = "lsm_bprm_check_security", sleepable = "true")]
pub fn bprm_check_security(ctx: LsmContext) -> i32 {
match try_bprm_check_security(ctx) {
Ok(ret) => ret,
Err(ret) => ret,
}
}
```
=> Add `BPF_F_SLEEPABLE` flag support to LSM

aya/Cargo.toml, aya/src/bpf.rs, aya/src/programs/xdp.rs
Putting dependabot out of its misery (see #589, #571, #549, #541).
=> build(deps): update bitflags requirement from 1.2.1 to 2.2.1

aya-obj/src/btf/btf.rs, aya-obj/src/btf/relocation.rs, aya-obj/src/relocation.rs
As per title, this patch drops unnecessary `mut`.
=> aya: drop unnecessary `mut`

aya-obj/src/obj.rs
That was missing from https://github.com/aya-rs/aya/commit/401ea5e8482ece34b6c88de85ec474bdfc577fd4.
=> aya-obj: Fix ProgramSection::from_str for bss and rodata sections

aya-obj/src/obj.rs, aya/src/bpf.rs, aya/src/sys/bpf.rs
Fix map creation failure when a BPF have a data section on older kernel. (< 5.2)
If the BPF uses that section, relocation will fail accordingly and report an error.
=> aya: Do not create data maps on kernel without global data support

.github/workflows/build-aya.yml, aya-log-common/src/lib.rs, aya-log-ebpf-macros/src/expand.rs, aya-log/src/lib.rs, aya-obj/src/relocation.rs, test/integration-ebpf/src/log.rs, test/integration-test/src/tests/log.rs
These only support LowerHex and UpperHex hints for now.
=> aya-log-common: support logging byte slices

xtask/src/codegen/aya_bpf_bindings.rs
This patch adds `user_regs_struct`.
riscv provides struct `user_regs_struct` instead of struct `pt_regs` to userspace.
After bindings generates the code, adding the riscv support in `bpf/aya-bpf/src/args.rs`
then aya-bpf could be built for riscv.
=> xtask: codegen: generate bindings for user_regs_struct

aya-bpf-macros/src/lib.rs
Added rust docs as discussed with @alessandrod .
=> docs(macros): add rust docs for cgroup_sock_addr macro

aya/src/maps/perf/async_perf_event_array.rs, aya/src/maps/perf/mod.rs, bpf/aya-bpf-cty/src/lib.rs
New lint rules is add in https://github.com/rust-lang/rust-clippy/pull/10763.
=> clippy: clean useless `any` in cfg

aya-log-common/src/lib.rs, aya-log-ebpf-macros/src/expand.rs, aya-log/src/lib.rs, bpf/aya-log-ebpf/src/lib.rs
Fix https://github.com/aya-rs/aya/issues/513
Currently, we are not checking in the log macro if a parameter can be formatted using a specific type of format, which can lead to a runtime panic. This PR implements validation logic in proc macro.
This will add the following code in the generated code:
This is a function that checks the type bound, and the function body is empty. When built with a release level optimization, e.g. `opt-level=3`, it will be optimized out.
Some tests
```Rust
unsafe fn try_xdp_hello(ctx: XdpContext) -> Result<u32, u32> {
// test default formatter
info!(&ctx, "test default formatter");
info!(&ctx, "i8 {}", 8);
info!(&ctx, "i16 {}", 16);
info!(&ctx, "i32 {}", 32);
info!(&ctx, "i64 {}", 64);
info!(&ctx, "isize {}", 128);
info!(&ctx, "u8 {}", 8);
info!(&ctx, "u16 …
```
=> feat(aya-log): check format and value type in proc macro

aya-obj/src/btf/btf.rs, aya-obj/src/obj.rs
Compiling a program using an older version of clang (tested w/ clang 8) for a non-CORE program creates a `.BTF` and a `.BTF.ext` section that aya fails to load.
* `.BTF.ext` error: the `.BTF.ext` section is from an older header and `aya` isn't checking the `hdr_len` and instead assumes that the size of its pregenerated struct will work no matter what. This PR fixes this by first loading the data into a "minimal header" and then only loads as much data into the full fledged header as it is allowed to per the spec. 
* `.BTF` error: The created section has no types which returns an error at load type saying "type not found". This PR uses the existing "sanitize" method to check if there are any types and if not then it skips the load of the `.BTF` section as there is no gain in trying to load …
=> Fix load errors for empty (but existent) BTF/BTF.ext sections

aya-log-common/src/lib.rs, aya-log-ebpf-macros/src/expand.rs, aya-log-parser/src/lib.rs, aya-log/src/lib.rs, test/integration-ebpf/src/log.rs
Having separate format hints and tokens per IP address family is unnecessary, since they are represented by different types and we handle format hints for each type separately. So we can just have one format hint.
Also, we should be consistent with the format strings grammar in Rust[0]. The `type` token, which is mapped to formatting traits, usually consists of one letter[1] (and optional `?` for `Debug` trait, but that doesn't matter for us). It shouldn't consist of multiple letters. Our `:ipv4` and `:ipv6` tokens were clearly breaking that convention, so we should rather switch to something with one letter - hence `:i`.
[0] https://doc.rust-lang.org/std/fmt/#syntax
[1] https://doc.rust-lang.org/std/fmt/#formatting-traits
=> aya-log: Unify IP format hints into one, repsesent it by `:i` token

aya-log-common/src/lib.rs, aya-log-ebpf-macros/src/expand.rs, bpf/aya-log-ebpf/src/lib.rs
aya-log-ebpf-macros was failing to compile because it was referencing a couple of `DisplayHint` variants that no longer exist. These were removed in #599.
```
Compiling aya-log-ebpf-macros v0.1.0 (/home/robert/aya/aya-log-ebpf-macros)
error[E0599]: no variant or associated item named `Ipv4` found for enum `DisplayHint` in the current scope
--> aya-log-ebpf-macros/src/expand.rs:93:22
|
93 |         DisplayHint::Ipv4 => parse_str("::aya_log_ebpf::macro_support::check_impl_ipv4"),
|                      ^^^^ variant or associated item not found in `DisplayHint`
error[E0599]: no variant or associated item named `Ipv6` found for enum `DisplayHint` in the current scope
--> aya-log-ebpf-macros/src/expand.rs:94:22
|
94 |         DisplayHint::Ipv6 => …
```
=> aya-log-ebpf-macros: fix compile errors

aya-obj/src/btf/btf.rs, aya-obj/src/btf/relocation.rs, aya-obj/src/lib.rs, aya-obj/src/obj.rs, aya-obj/src/relocation.rs, aya/src/bpf.rs, aya/src/programs/mod.rs, test/integration-test/src/tests/btf_relocations.rs, test/integration-test/src/tests/rbpf.rs
This fix aya wrong logic causing non entrypoint functions to not have any BTF relocations working.
As a result, I needed to refactor how functions are stored and handled.
I also fixed missing section_offset computation for instruction offset in multiple spots.
=> aya: Apply BTF relocations to all functions

aya-obj/src/btf/relocation.rs, test/integration-test/src/tests/btf_relocations.rs
Missing relocations at load time shouldn't cause an error in `aya-obj` but instead poison related instructions.
This makes struct flavors work.
Close #533
=> aya-obj: Make relocations less strict

.github/workflows/build-aya-bpf.yml, .github/workflows/build-aya.yml, .github/workflows/gen.yml
I don't understand why, but dependabot isn't updating this. See
https://github.com/dependabot/dependabot-core/issues/7384.
=> github: update Swatinem/rust-cache@{v1,v2}

aya/src/programs/probe.rs
There was two issues here:
1. the `fn_name` wasn't sanitized causing issue with uprobe library paths.
2. `uretprobe` needs the offset to be feed as `fn_name` is the library name.
Fix uprobe support on Ubuntu 18.04.
=> aya: Fix uprobe support on 4.16 and lower

aya/src/util.rs
These two functions are needed because kernel symbols representing syscalls have architecture-specific prefixes.
These are the equivalent of bcc's get_syscall_fnname and get_syscall_prefix.
Solves: #534
Inspired by https://github.com/iovisor/bcc/blob/a078cbc7cfbdcee88c9cf3e2b76c2c8c1517e478/src/python/bcc/__init__.py#L804
=> aya-utils: add syscall_prefix and syscall_fnname_add_prefix

aya-obj/src/obj.rs, aya/src/bpf.rs
This allow to not error out when a global symbol is missing from the object.
=> aya: allow global value to be optional

aya/src/maps/lpm_trie.rs
Based on the discussion in Discord[1] we've decided to drop the
iter_keys() API for LPM Trie. According to the kernel self-tests and
experimentation done in Aya, providing a key into bpf_map_get_next_id
will either:
- If key is an EXACT match, proceed iterating through all keys in the
trie from this point
- If key is NOT an EXACT match, proceed iterating through all keys in
the trie starting at the leftmost entry.
An API in Aya *could* be crafted that gets the LPM match + less specific
matches for a prefix using these semantics BUT it would only apply to
userspace. Therefore we've opted out of fixing this.
[1]: https://discord.com/channels/855676609003651072/855676609003651075/1075034125158842411
=> aya: Remove iter_key from LPM Trie API

aya-obj/src/btf/btf.rs, aya-obj/src/obj.rs, aya-obj/src/relocation.rs, aya/src/bpf.rs, aya/src/programs/perf_attach.rs, aya/src/sys/bpf.rs
This commit adds a new probe for bpf_attach_cookie, which would be used to implement USDT probes. Since USDT probes aren't currently supported, this triggers a dead_code warning in clippy.
There are cases where exposing FEATURES - our lazy static - is actually helpful to users of the library. For example, they may wish to choose to load a different version of their bytecode based on current features. Or, in the case of an orchestrator like bpfd, we might want to allow users to describe which features their program needs and return nice error message is one or more nodes in their cluster doesn't support the necessary feature set.
=> aya: Make FEATURES public

bpf/aya-bpf/src/helpers.rs, bpf/aya-bpf/src/lib.rs, test/integration-ebpf/Cargo.toml, test/integration-ebpf/src/bpf_probe_read.rs, test/integration-test/src/tests/bpf_probe_read.rs, test/integration-test/src/tests/mod.rs
This change does a few things:
- it fixes a bug in the wrappers, where we were expecting the kernel to return len=1 for b"\0" where it instead returns 0 and doesn't write out the NULL terminator
- it makes the helpers more robust by hardcoding bound checks in assembly so that LLVM optimizations can't transform the checks in a way that the verifier can't understand
- it adds integration tests
=> bpf: improve bpf_probe_read_kernel_str_bytes and bpf_probe_read_user_str_bytes

aya-obj/src/btf/types.rs
Useful for shenanigans with CO-RE.
=> misc: aya-obj: Make it possible to externally assemble BtfEnum

.github/workflows/build-aya-bpf.yml, bpf/aya-bpf-cty/src/lib.rs, bpf/aya-bpf/src/args.rs, bpf/aya-bpf/src/programs/probe.rs
This patch introduces `pt_regs` handling in aya-bpf/args.rs for
the riscv64 architecture. The current CI is disabled for riscv64
because this implementation is missing.
=> bpf: Add `pt_regs` handling in aya-bpf/args.rs for riscv64

aya-obj/src/btf/btf.rs, aya/Cargo.toml, aya/src/maps/mod.rs, aya/src/programs/cgroup_device.rs, aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/cgroup_sysctl.rs, aya/src/programs/mod.rs, aya/src/programs/probe.rs, aya/src/programs/xdp.rs, aya/src/sys/bpf.rs, aya/src/util.rs, test/integration-test/Cargo.toml, test/integration-test/tests/btf_relocations.rs, test/integration-test/tests/load.rs, test/integration-test/tests/smoke.rs
- Remove verifier log special case
- Remove procfs dependency
- Rewrite kernel version logic
This restores and enhances the logic originally added in #579.
=> Remove procfs dependency

aya/src/programs/kprobe.rs, aya/src/programs/links.rs, aya/src/programs/perf_event.rs, aya/src/programs/trace_point.rs, aya/src/programs/uprobe.rs, test/integration-ebpf/src/test.rs, test/integration-test/src/tests/load.rs, test/run.sh
Implement TryFrom functions to convert Fdlink to PerfLink/TracePointLink/ KprobeLink, and UprobeLink and vice-versa.
This allows us to pin taken links for perf programs, ultimately ensuring the link isn't dropped when the loading process exits.
Required for https://github.com/redhat-et/bpfd/issues/306
TODO: It'd be nice to add some documentation around this API somewhere...
```
let mut bpf = BpfLoader::new()
// load pinned maps from /sys/fs/bpf/my-program
.map_pin_path("/sys/fs/bpf")
// finally load the code
.load_file("/home/astoycos/go/src/github.com/redhat-et/bpfd/examples/go-tracepoint-counter/bpf_bpfel.o")?;
let program: &mut TracePoint = bpf.program_mut("tracepoint_kill_recorder").unwrap().try_into()?;
program.load()?;
let link_id = program.attach("syscalls", "sys_enter_kill")?; …
```
=> Implement FdLink conversions

aya/src/bpf.rs, aya/src/maps/mod.rs
Just because aya doesn't support working with some map types doesn't mean we should't allow them to be loaded.
Add a new `Unsupported` map type to facilitate this, also add a debug log to let the user know we just loaded and unsupported map type.
=> Add Unsupported Map type

bpf/.cargo/config.toml
So to build/check things using the bpf target one can:
cd bpf && cargo check && cargo build
without having to manually pass --target=bpfel-unknown-none -Z build-std=core.
It also fixes cargo xtask docs, since the command relies on bpf docs being built with the bpfel-unknown-none target.
=> Add back bpf/.cargo/config.toml

aya/src/bpf.rs
This fix BpfLoader::load logic by following what libbpf does.
Required for Debian 10 support.
=> aya: Ignore embedded BTF error if not truely required

.cargo/config.toml, .github/workflows/build-aya-bpf.yml, .github/workflows/build-aya.yml, .github/workflows/lint.yml, .github/workflows/release.yml, Cargo.toml, aya-log-common/src/lib.rs, aya-log-parser/src/lib.rs, aya-log/src/lib.rs, aya-obj/src/lib.rs, aya/Cargo.toml, aya/src/maps/mod.rs, aya/src/maps/perf/async_perf_event_array.rs, aya/src/maps/perf/mod.rs, aya/src/programs/links.rs, bpf/aya-bpf/src/helpers.rs, bpf/aya-bpf/src/programs/sk_buff.rs, bpf/aya-bpf/src/programs/tc.rs, test/integration-test/Cargo.toml
=> Remove async feature; misc test cleanup

test/integration-test/src/tests/log.rs
Presently when this test fails you just get "5 items instead of 6" but
not which item was lost.
See failures in https://github.com/aya-rs/bpf-linker/pull/72.
=> Make logging test output more legible

test/integration-ebpf/rust-toolchain.toml, test/integration-test/build.rs
The ebpf probes require a nightly compiler. Before this change, if you ran `cargo xtask integration-test` with a stable compiler toolchain as default, or you ran `cargo +stable xtask integration-test`, you would have seen an error like the one below. This is now fixed.
```
--- stderr
/home/ajwerner/src/github.com/aya-rs/aya/test/integration-test/bpf/ring_buf_sched_tracepoint.bpf.c:18:21: warning: declaration of 'struct switch_args' will not be visible outside of this function [-Wvisibility]
int bpf_prog(struct switch_args* ctx)
^
1 warning generated.
error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
thread 'main' panicked …
```
=> test/integration-test: use +nightly for ebpf

Cargo.toml, aya-bpf-macros/Cargo.toml, aya-log-common/Cargo.toml, aya-log-ebpf-macros/Cargo.toml, aya-log-parser/Cargo.toml, aya-log/Cargo.toml, aya-obj/Cargo.toml, aya-tool/Cargo.toml, aya/Cargo.toml, test/integration-test/Cargo.toml, xtask/Cargo.toml
This way we will avoid version mismatches and make differences in features across our crates clearer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/667)
=> cargo: Define dependencies on the workspace level

.github/workflows/ci.yml, test/integration-test/build.rs, test/run.sh, xtask/src/run.rs
=> integration-test: shuttle linker logs to user

aya-log-ebpf-macros/src/expand.rs
This happens to fix the miscompilation that occurs when bpf-linker is
moved to LLVM's new pass manager. A later commit will avoid the
miscompilation more convincingly.
=> Refactor log macro for readability

.github/workflows/ci.yml, test/integration-test/src/tests/bpf_probe_read.rs, test/integration-test/src/tests/log.rs, test/integration-test/src/tests/relocations.rs, test/run.sh
In release, the trigger functions were being optimized out and the tests did not work. Use core::hint::black_box to ensure that the functions are not optimized out. Also, run these integration tests in CI to ensure that we don't regress.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/661)
=> integration-tests: run in release also

xtask/src/public_api.rs
This is currently producing inverse diffs.
=> xtask: reverse public API diff direction

test/integration-test/build.rs
=> integration-test: Remove RUSTC from cargo-in-cargo

aya/Cargo.toml, aya/src/bpf.rs, aya/src/maps/bloom_filter.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/maps/perf/perf_buffer.rs, aya/src/maps/perf/perf_event_array.rs, aya/src/maps/sock/mod.rs, aya/src/maps/sock/sock_hash.rs, aya/src/programs/links.rs, aya/src/programs/mod.rs, aya/src/programs/perf_attach.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/sock_ops.rs, aya/src/programs/socket_filter.rs, aya/src/programs/utils.rs, aya/src/programs/xdp.rs, aya/src/sys/bpf.rs, aya/src/sys/fake.rs, aya/src/sys/mod.rs, aya/src/sys/netlink.rs, aya/src/sys/perf_event.rs
This PR is meant as the first step towards using `OwnedFd` where possible instead of `RawFd` to be more foolproof and safer to use. This PR tackles the BTF file descriptor that is loaded when the object has a BTF section and fixes an existing file descriptor leak as that file descriptor was never being closed. Since we are moving to use `OwnedFd` this close will now happen by default. 
The returned file descriptor will be wrapped in an `Arc` so that it can be shared across programs and maps of the loaded BPF file with no user-visible impact (no breaking changes). 
As an add-on I also changed the `Cargo/toml` to be explicit about the MSRV. This had been previously bumped by https://github.com/aya-rs/aya/pull/633 by using the [`std::os::fd`](https://doc.rust-lang.org/stable/std/os/fd/index.h …
=> Use `OwnedFd` for BTF's file descriptor

aya-obj/src/btf/btf.rs, aya-obj/src/lib.rs, aya/src/programs/mod.rs, aya/src/sys/bpf.rs, test/integration-test/build.rs, xtask/public-api/aya-obj.txt, xtask/public-api/aya.txt
- integration-test: rerun-if-changed=integration-ebpf
- Do not escape newlines on Err(LoadError).unwrap()
=> Misc testing improvements

Cargo.toml, aya/src/lib.rs, aya/src/sys/mod.rs, aya/src/sys/netlink.rs, test/integration-test/Cargo.toml, test/integration-test/src/lib.rs, test/integration-test/src/tests/smoke.rs, test/integration-test/src/utils.rs
For tests that do networking operations, this allows to have a clean-state network namespace and interfaces for each test. Mainly, this avoids "device or resource busy" errors when reusing the loopback interface across tests.
=> test: add the possibility to run a test inside a network namespace

aya-obj/src/btf/btf.rs, aya-obj/src/btf/relocation.rs, aya-obj/src/btf/types.rs, aya-obj/src/obj.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/perf/perf_buffer.rs, aya/src/sys/mod.rs, test/integration-test/src/tests/elf.rs
Always include operands in failing assertions. Use assert_matches over
manual match + panic.
=> all: better panic messages

aya/src/maps/perf/perf_buffer.rs, aya/src/programs/perf_attach.rs, aya/src/programs/perf_event.rs, aya/src/programs/probe.rs, aya/src/programs/trace_point.rs, aya/src/sys/mod.rs, aya/src/sys/perf_event.rs
This fixes a file descriptor leak when creating a link of BPF_PERF_EVENT attach type.
=> aya: Return `OwnedFd` for `perf_event_open`.

.github/workflows/ci.yml, Cargo.toml, aya/src/programs/links.rs, test/README.md, test/integration-test/Cargo.toml, test/integration-test/bpf/reloc.bpf.c, test/integration-test/bpf/reloc.btf.c, test/integration-test/build.rs, test/integration-test/src/lib.rs, test/integration-test/src/tests/bpf_probe_read.rs, test/integration-test/src/tests/btf_relocations.rs, test/integration-test/src/tests/rbpf.rs, test/run.sh
Move the use of clang and llvm-objcopy from run-time to build-time. This
allows the integration tests to run on VMs with simpler userlands.
Create a new CI job to build the integration tests separately from
running them. Ship them from that job to the runner job using github
actions artifacts.
=> integration-test: Remove runtime toolchain deps

aya-bpf-macros/src/args.rs, aya-bpf-macros/src/btf_tracepoint.rs, aya-bpf-macros/src/cgroup_skb.rs, aya-bpf-macros/src/cgroup_sock.rs, aya-bpf-macros/src/cgroup_sock_addr.rs, aya-bpf-macros/src/cgroup_sockopt.rs, aya-bpf-macros/src/fentry.rs, aya-bpf-macros/src/fexit.rs, aya-bpf-macros/src/kprobe.rs, aya-bpf-macros/src/lib.rs, aya-bpf-macros/src/lsm.rs, aya-bpf-macros/src/map.rs, aya-bpf-macros/src/raw_tracepoint.rs, aya-bpf-macros/src/tracepoint.rs, aya-bpf-macros/src/uprobe.rs, aya-bpf-macros/src/xdp.rs, aya-obj/src/obj.rs, aya/src/bpf.rs, xtask/public-api/aya-obj.txt
This PR contains a number of commits that clean up aya-bpf-macros after their recent refactor.
The bulk of the PR is in aya-bpf-macros where I've added the ability to parse `bool` attributes.
This is neat as args are permitted in any order, and can be mixed with K/V style arguments.
For example, `sleepable, function = "foo"` and `function = "foo", sleepable` are both permitted.
Per https://kernel.org/doc/html/latest/bpf/libbpf/program_types.html I added support to all sleepable program types since this was already done at the macro-level for LSM. This required changes in aya-obj and aya.
The other major change is that `pop_required_args` is now gone, and all things that were "required" before are now Options. We may make these required one day, but not just yet.
- - -
This change is [<img …
=> Tidy up aya-bpf-macros (again)

aya/src/programs/uprobe.rs, test/integration-test/src/tests/load.rs
See individual commits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/717)
=> uprobe,integration-test: do not exercise dylib resolution in integration tests

aya/src/programs/uprobe.rs
This attempts to do fewer lossy conversions and to avoid some
allocations.
=> uprobe: refactor target resolution 

aya/src/maps/stack_trace.rs, aya/src/util.rs, xtask/public-api/aya.txt
Makes symbol resolution a trait. Begins to address #705 and extend #339, allows users to define custom implementations in the meantime.
=> Segment out SymbolResolver to a trait

aya-obj/src/obj.rs, aya/src/bpf.rs, test/integration-test/src/tests/rbpf.rs, xtask/public-api/aya-obj.txt
The name here is never used as we get the program name from the symbol table instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/720)
=> aya-obj: Remove name from ProgramSection

aya/src/maps/mod.rs, aya/src/programs/cgroup_device.rs, aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/cgroup_sysctl.rs, aya/src/programs/extension.rs, aya/src/programs/kprobe.rs, aya/src/programs/links.rs, aya/src/programs/mod.rs, aya/src/programs/perf_attach.rs, aya/src/programs/perf_event.rs, aya/src/programs/sk_lookup.rs, aya/src/programs/trace_point.rs, aya/src/programs/uprobe.rs, aya/src/programs/utils.rs, aya/src/programs/xdp.rs, aya/src/sys/bpf.rs, xtask/public-api/aya.txt
I had to add a few `into_raw_fd()` to avoid ballooning up this PR with changes to `MapData` or to `ProgramData` (because the syscall to `BPF_OBJ_GET` now returns an `OwnedFd`) Those are more involved so they should each be their own PR. 
As far as I could tell there weren't any leaked file descriptors being fixed by this, this is just future proofing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/709)
=> aya: Use OwnedFd in FdLink.

aya-obj/src/obj.rs, test/integration-test/bpf/reloc.bpf.c
This commit fixes the (func|line)_info when we have multiple programs in the same section. The integration test reloc.bpf.c serves as our test case here. This required filtering down the (func|line)_info to only that in scope of the current symbol + then adjusting the offets to appease the kernel.
The C code was formatted with clang-format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/721)
=> aya: Fix (func|line)_info multiple progs in section

aya-obj/src/btf/types.rs
Rather than creating an empty vector and iteratively appending - which
might induce intermediate allocations - create an ExactSizeIterator and
collect it into a vector, which should produce exactly one allocation.
=> btf: avoid multiple vector allocations

aya-obj/src/btf/btf.rs
The BTF we're working on is Cow anyway so modifying in-place is fine. All we need to do is store some information before we start our mutable iteration to avoid concurrently borrowing types both mutably and immutably.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/731)
=> aya-obj: Mutate BTF in-place without clone

aya-log-common/src/lib.rs, test/integration-ebpf/src/log.rs, test/integration-test/src/tests/log.rs, xtask/public-api/aya-log-common.txt
Some of these functions fail to compile when not inlined, so we should
be explicit.
Before deciding on this approach I tried various ways of making all
these functions #[inline(never)] to save instructions but I ran into
blockers:
- These functions currently return Result, which is a structure. This is
not permitted in BPF.
- I tried inventing a newtype that is a #[repr(transparent)] wrapper of
u16, and having these functions return that; however it seems that
even if the object code is legal, the verifier will reject such
functions because the BTF (if present, and it was in my local
experiments) would indicate that the return is a structure.
- I tried having these functions return a plain u16 where 0 means error,
but the verifier still rejected the BTF because the receiver (even if
made …
=> log: annotate logging functions inlining

aya-log-common/src/lib.rs, aya-log-ebpf-macros/src/expand.rs, aya-log/src/lib.rs, xtask/public-api/aya-log-common.txt
`Option<NonZeroUsize>` is guaranteed to have the same size as `usize`, which
is not guaranteed for `Result`. This is a minor optimization, but also
results in simpler code.
=> aya-log: s/Result<usize, ()>/Option<NonZeroUsize>/

aya-log/src/lib.rs
This avoids an atomic load on every log.
=> Remove pointless DefaultLogger

aya-log-common/src/lib.rs, xtask/src/run.rs
It seems these go to stderr, not stdout. Use `Ctrl-A x` to shut QEMU
down if a panic is seen.
=> xtask: watch for kernel panics on stderr

aya/src/maps/stack_trace.rs, aya/src/util.rs, xtask/public-api/aya.txt
~~Currently, the stack trace API has no way to handle inlined function names. This change swaps out the `Option<Cow<'_, str>>` with a `ResolvedSymbol` type, which is capable of representing unresolved, uninlined, and inline function resolution.~~
~~Note that I have explicitly opted to use `String` and not `Cow<str>` as there is no existing use case where the user does not want an owned version of the symbol name. Similarly, I couldn't think of a situation where this is possible (since the lifetime of the stack frame is not bindable from `resolve_symbol`).~~
As discussed in the Discord, it is likely better to extract this behaviour to another crate. This PR discards everything relating to explicit support of symbol resolution.
This PR makes breaking API changes.
=> Revisit the stack trace API to remove resolution support

aya/src/programs/extension.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/mod.rs, aya/src/sys/bpf.rs
Allows the caller to pass a slice which the kernel will populate with
map ids used by the program.
=> sys: add map_ids to bpf_prog_get_info_by_fd

aya/src/programs/extension.rs, aya/src/programs/mod.rs, aya/src/sys/bpf.rs
`ProgramData::attach_btf_obj_fd` is now owned.  This means that
`ProgramData` now closes the file descriptor on drop.
Updates #612.
=> programs: Plug attach_btf_obj_fd leak

aya/src/bpf.rs, aya/src/maps/bloom_filter.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/sys/bpf.rs, xtask/public-api/aya.txt
This is only used in create and therefore can be passed
as a parameter.
=> aya: Don't store btf_fd in MapData

aya/src/programs/lirc_mode2.rs, aya/src/programs/mod.rs, aya/src/programs/utils.rs, test/integration-test/src/tests/smoke.rs, xtask/public-api/aya.txt
This PR adds some helpful methods to the `ProgramInfo` aya structure.  More specifically we start by adding helpers to extract the following information in usable format from `bpf_prog_info`
```
"Name",
"Id",
"Type",
"Name",
"Loaded-At",
"Tag",
"Gpl-compatible",
"Map-ids",
"Btf-id",
"Bytes_xlated",
"Jited",
"Bytes_jited",
"Bytes_memlock",
"Verified_insns",
``` 
This is in line with the information extracted by the popular [bpftool](https://github.com/libbpf/bpftool) binary 
bpfd is using these commits downstream in 
https://github.com/bpfd-dev/bpfd/pull/570
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/637)
=> Add more helpful methods to `ProgramInfo`

aya/src/maps/array/program_array.rs, aya/src/maps/perf/async_perf_event_array.rs, aya/src/programs/cgroup_device.rs, aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/cgroup_sysctl.rs, aya/src/programs/extension.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/mod.rs, aya/src/programs/perf_event.rs, aya/src/programs/probe.rs, aya/src/programs/sk_lookup.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/sock_ops.rs, aya/src/programs/socket_filter.rs, aya/src/programs/tc.rs, aya/src/programs/trace_point.rs, aya/src/programs/utils.rs, aya/src/programs/xdp.rs, aya/src/sys/bpf.rs, xtask/public-api/aya.txt
`ProgramData::fd` is now also owned. This means that `ProgramData` now
closes the file descriptor on drop. In the future we might consider
making `ProgramFd` hold a `BorrowedFd` but this requires API design work
due to overlapping borrows.
Since `ProgramFd` is no longer `Copy`, update methods to take it by
reference to allow callers to use it multiple times as they are
accustomed to doing.
This is an API breaking change.
Updates #612.
=> programs: `ProgramFd` is owned

aya-obj/src/relocation.rs, aya/src/bpf.rs, aya/src/maps/array/array.rs, aya/src/maps/array/per_cpu_array.rs, aya/src/maps/array/program_array.rs, aya/src/maps/bloom_filter.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/hash_map/mod.rs, aya/src/maps/hash_map/per_cpu_hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/maps/perf/perf_event_array.rs, aya/src/maps/queue.rs, aya/src/maps/sock/sock_hash.rs, aya/src/maps/sock/sock_map.rs, aya/src/maps/stack.rs, aya/src/maps/stack_trace.rs, aya/src/sys/bpf.rs, test/integration-test/src/tests/rbpf.rs, xtask/public-api/aya-obj.txt, xtask/public-api/aya.txt
The primary driver of change here is that `MapData::create` is now a
factory function that returns `Result<Self, _>` rather than mutating
`&mut self`. The remaining changes are consequences of that change, the
most notable of which is the removal of several errors which are no
longer possible.
=> aya: MapData::fd is non-optional

.github/workflows/ci.yml, aya/src/maps/mod.rs, aya/src/maps/perf/mod.rs
Appease the new lint rustdoc::redundant_explicit_links that was added in
https://github.com/rust-lang/rust/pull/113167.
=> aya: fix docs build

test/integration-ebpf/Cargo.toml, test/integration-ebpf/build.rs, xtask/src/lib.rs
https://github.com/rust-lang/cargo/pull/12369 fixed this bug and was
picked up in https://github.com/rust-lang/rust/pull/114027.
=> integration-test: Remove cargo symlink workaround

aya-obj/src/obj.rs, aya-obj/src/programs/cgroup_sock.rs, aya-obj/src/programs/cgroup_sock_addr.rs, aya-obj/src/programs/cgroup_sockopt.rs
Remove repetition of permitted cgroup attach types. Make optionality of
name more explicit rather than pretending both kind and name are equal
to section.
=> aya-obj: reduce indirection in section parsing

aya/src/maps/sock/mod.rs, aya/src/programs/cgroup_device.rs, aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/cgroup_sysctl.rs, aya/src/programs/extension.rs, aya/src/programs/links.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/mod.rs, aya/src/programs/perf_attach.rs, aya/src/programs/perf_event.rs, aya/src/programs/probe.rs, aya/src/programs/sk_lookup.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/sock_ops.rs, aya/src/programs/socket_filter.rs, aya/src/programs/tc.rs, aya/src/programs/trace_point.rs, aya/src/programs/utils.rs, aya/src/programs/xdp.rs, aya/src/sys/bpf.rs, aya/src/sys/netlink.rs, xtask/public-api/aya.txt
This PR is divided into two commits:
1. Use `OwnedFd` inside `ProgramData` to ensure file descriptor safety.
2. Use `AsFd` when attaching programs externally and save them as `OwnedFd` internally. 
This PR tries to limit the amount of breaking changes as much as possible, in that the signatures are changing but in practice none or very little changes would be required as a user. This is highlighted by the fact that none of the tests and only one of the doctests had be be touched. The one doctest that was touched was due to the fact that the doctest was explicitely calling for `as_raw_fd()` on a `TcpStream` for attaching to a socket filter program but this function now accepts anything that implemented `AsFd` so the change was just to remove the explicit call to `as_raw_fd()` and instead …
=> File descriptor safety for program fd + prog attaching

aya/src/maps/mod.rs, xtask/public-api/aya.txt
The old macros were repetitive and inflexible. This unifies the various
macros used to generate TryFrom implementations for map implementations
from the relevant map enum variants.
Cleanup in anticipation of fixing https://github.com/aya-rs/aya/issues/636.
The API changes are just about renaming the return to Self and
Self::Error; they are not real changes.
=> aya/maps: rework TryFrom macros

aya/src/maps/perf/async_perf_event_array.rs, aya/src/maps/perf/perf_event_array.rs, xtask/public-api/aya.txt
=> async_perf_event_array: access inner through async

aya-obj/src/lib.rs, aya-obj/src/relocation.rs, aya/src/bpf.rs, aya/src/maps/array/array.rs, aya/src/maps/array/per_cpu_array.rs, aya/src/maps/array/program_array.rs, aya/src/maps/bloom_filter.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/hash_map/mod.rs, aya/src/maps/hash_map/per_cpu_hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/maps/perf/perf_event_array.rs, aya/src/maps/queue.rs, aya/src/maps/sock/mod.rs, aya/src/maps/sock/sock_hash.rs, aya/src/maps/sock/sock_map.rs, aya/src/maps/stack.rs, aya/src/maps/stack_trace.rs, aya/src/programs/links.rs, aya/src/programs/mod.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/utils.rs, aya/src/sys/bpf.rs, test/integration-test/src/tests/rbpf.rs, xtask/public-api/aya-obj.txt, xtask/public-api/aya.txt
`MapData::fd` is now a `MapFd`. This means that `MapData` now closes the
file descriptor on drop. In the future we might consider making `MapFd`
hold a `BorrowedFd` but this requires API design work due to overlapping
borrows.
Since `SockMapFd` is no longer `Copy`, attach methods to take it by
reference to allow callers to use it multiple times as they are
accustomed to doing.
`SockMapFd` implements `try_clone`. `MapFd` and `SockMapFd` are now
returned by reference to allow callers to avoid file descriptor cloning
when desired.
This is an API breaking change.
Updates #612.
=> maps: `MapFd` and `SockMapFd` are owned

aya/src/programs/mod.rs, xtask/public-api/aya.txt
Add a new api to the outer level `Program` structure which allows users to get the program's kernel info before casting it to an explicit program variant.
=> aya: add program_info() api to `Program`

aya/src/maps/mod.rs, aya/src/pin.rs, xtask/public-api/aya.txt
This is 2 small changes.
The first removes tracking of whether or not a Map has been pinned from MapData.
This is unnecessary since Maps may be pinned multiple times to multiple locations on a BPF filesystem.
The second change makes MapData::pin part of the public API.
This is to solve a use-case where a user (in this case bpfd) may want to:
- `MapData::from_pin` to open a pinned map from bpffs
- `MapData::pin` to pin that object into another bpffs
Both operations should be easily accomplished without needing to cast a `MapData` into a concrete Map type - e.g aya::maps::HashMap.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/790)
=> Remove MapData::pinned. Make MapData::pin public

.github/workflows/ci.yml
- .github: remove 6.4.x kernel tests
- .github: run tests nightly
=> Remove 6.4.x kernels from CI

xtask/src/docs.rs, xtask/src/run.rs
- xtask: appease new clippy warning
- xtask: remove useless copy
=> appease clippy

aya/src/programs/mod.rs, aya/src/util.rs
This fixes an issue that made aya not able to load eBPF programs on kernels with a patch number greater than 255. 
I noticed this when trying to load some eBPF programs on an AWS instance running a `4.14.304-226.531.amzn2.x86_64` kernel. The kernel code that it tried to load was for a 4.15 kernel instead which caused a verifier error. 
I considered doing this directly in the `KernelVersion::current` function but per the comments in: https://github.com/torvalds/linux/commit/9b82f13e7ef316cdc0a8858f1349f4defce3f9e0 it looks like the clamp should only be applied for the context of creating the `LINUX_VERSION_CODE` so I limited the fix to only the calculating of the code for bpf prog loading.
=> aya: Fix program loading on kernels with a patch > 255

test/integration-test/src/tests/load.rs
The test could fail due to the lack of clock monotonicity. This PR deflakes the test by adding retries.
See
https://github.com/aya-rs/aya/actions/runs/6340369670/job/17221591723.
=> integration-test: deflake test_loaded_at

aya/src/bpf.rs, aya/src/maps/array/array.rs, aya/src/maps/array/per_cpu_array.rs, aya/src/maps/array/program_array.rs, aya/src/maps/bloom_filter.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/hash_map/per_cpu_hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/maps/queue.rs, aya/src/maps/sock/sock_hash.rs, aya/src/maps/stack.rs, aya/src/maps/stack_trace.rs, aya/src/maps/xdp/cpu_map.rs, aya/src/maps/xdp/dev_map.rs, aya/src/maps/xdp/dev_map_hash.rs, aya/src/maps/xdp/xsk_map.rs, test/integration-test/bpf/multimap-btf.bpf.c, test/integration-test/src/tests/load.rs, test/integration-test/src/tests/rbpf.rs, xtask/public-api/aya.txt
Align with libbpf's  LIBBPF_PIN_BY_NAME map flag behavior.  More specifically if `map_pin_path` is not provided but a program has a map defined with the flag, pin it in `/sys/fs/bpf` otherwise pin it in the path provided by `map_pin_path(P)`.
Additionally, allow users to manually manage map pinning much like we do already for `Programs`, see commit messages for more details.
TODO support the pinning api for PerfEventArray's and AsyncPerfEventArray's
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/783)
=> aya: Implement dedicated map pinning

aya-log-ebpf-macros/src/expand.rs, test/integration-ebpf/src/log.rs, test/integration-test/src/tests/log.rs
Before this change we leaked some bindings to the calling scope, so for instance logging a variable named "len" led to a compile error.
=> aya-log: fix hygiene

Cargo.toml, test/integration-test/Cargo.toml, test/integration-test/src/tests/bpf_probe_read.rs, test/integration-test/src/tests/elf.rs, test/integration-test/src/tests/load.rs, test/integration-test/src/tests/log.rs, test/integration-test/src/tests/rbpf.rs, test/integration-test/src/tests/relocations.rs, test/integration-test/src/tests/ring_buf.rs, test/integration-test/src/tests/smoke.rs, test/integration-test/src/tests/xdp.rs
Use test_log::test so setting RUST_LOG=aya=debug works and it's easier to debug failures.
Note that sadly this doesn't work for tests that use the `test_case` macro since it hardcodes the stock rust #[test] attribute internally.
=> integration-tests: enable logs

aya-obj/src/obj.rs
Fixes a bug introduced by https://github.com/aya-rs/aya/pull/413 where we were generating a bunch of spurious LBB* programs.
=> aya: don't parse labels as programs

aya/Cargo.toml
Not using the `dep:` syntax created a Cargo feature flag for async-io, though this feature alone does nothing without the `async_std` or `async_tokio` features.
=> aya: fix unused async-io dependency linter error

aya-bpf-macros/src/args.rs
```
warning: accessing first element with `args.args.get(0)`
--> aya-bpf-macros/src/args.rs:71:24
|
71 |     if let Some(arg) = args.args.get(0) {
|                        ^^^^^^^^^^^^^^^^ help: try: `args.args.first()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#get_first
= note: `#[warn(clippy::get_first)]` on by default
```
Appears https://github.com/rust-lang/rust-clippy/commit/31fd282732e15811 has just landed in nightly.
=> aya-bpf-macros: appease clippy

bpf/aya-bpf-cty/src/lib.rs
This triggers the unused import lint after
https://github.com/rust-lang/rust/commit/482275b19422b871b986ec0400257a.
=> aya-bpf-cty: remove empty module

xtask/src/run.rs
We're seeing test failures where KVM is present but we aren't able to use it.
See https://github.com/actions/runner-images/issues/7670#issuecomment-1760184162.
=> xtask: attempt to open /dev/kvm

.github/workflows/ci.yml, .markdownlint-cli2.yaml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, aya/README.md, bpf/aya-bpf-cty/README.md, test/README.md
This adds a linter to catch common markdown formatting errors.
The linter used is markdownlint-cli2 which is available on all platforms
and has an associated Github Action to automate these checks in CI.
Configuration is checked in at .markdownlint-cli2.yaml.
You may run the check locally using `markdownlint-cli2`.
Or you may install the extension for VSCode:
DavidAnson.vscode-markdownlint
=> .github: Add markdownlint

aya/src/util.rs, xtask/public-api/aya.txt
I need to be able to access the current kernel version code so I can make some decisions  in user space and/or send the information to the eBPF programs to make the decisions. 
I could re-implement the logic to get the kernel version myself but since `aya` already has all the logic and is well tested I figured it made the most sense to expose the method I had previously implemented here. Another alternative would be to expose the fields inside `KernelVersion` but that felt like a bigger surface area to guarantee no breaking changes rather than just the one method. 
Maybe in the future we should implement the `__kconfig` stuff that libbpf and cilium allow so that the eBPF programs will know the `KERNEL_VERSION_CODE` but that felt heavyweight to implement at the moment and I wasn't sure if …
=> aya: make KernelVersion::code public

aya/src/maps/mod.rs, aya/src/programs/mod.rs, aya/src/sys/bpf.rs, aya/src/util.rs, test/integration-test/src/tests/smoke.rs, xtask/public-api/aya.txt
This change adds additional getter functions to Aya's BPF objects to extract the map ids of a loaded program and extract the map name from a loaded map. It also supports loading a map object by fd, similar to what already exists for program objects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/675)
=> Add helpers for querying info from existing bpf programs

Cargo.toml, test/integration-test/Cargo.toml, test/integration-test/src/tests/xdp.rs
This is a follow-up PR to https://github.com/aya-rs/aya/pull/527 where the AF_XDP integration test got dropped due to them depending on libbpf. We use the `xdpilone` crate there that is a pure-rust AF_XDP userspace library.
=> tests: add AF_XDP test using xdpilone

aya-log-parser/src/lib.rs
Extending log parser with the support for formatting pointers.
=> aya-log-parser: add support of :p format

test/integration-test/src/tests/xdp.rs
While `repr(Rust)` should not be an issue here, its data layout is only partially defined and allowed to change. Using `repr(transparent)` does not allow specifying the alignment. This leaves `repr(C)` as the way to define the data layout.
=> tests: change AF_XDP test `PacketMap` repr to `C`

aya/src/maps/ring_buf.rs, xtask/public-api/aya.txt
There was no reason for them not to be -- the APIs all require mutable references and hold onto mutable references, so there cannot be internal concurrency. The !Send + !Sync came from the MMap, but not for any good reason.
=> maps/ringbuf: make RingBuf: Send + Sync

aya/src/maps/mod.rs, aya/src/maps/perf/async_perf_event_array.rs, aya/src/maps/perf/perf_event_array.rs, test/integration-test/src/tests/load.rs, xtask/public-api/aya.txt
Implement pinning for perf_event_array and async_perf_event_array. Additionally make the core MapData.pin method operate on a reference rather than a mutable reference.
TODO from #783
=> aya/maps: pin for (async)perf_event_array

xtask/src/public_api.rs
```
CARGO_CFG_BPF_TARGET_ARCH=x86_64 cargo +nightly xtask public-api --bless --target x86_64-unknown-linux-gnu
```
=> xtask: allow public-api regen on aarch64-apple-darwin

.github/workflows/ci.yml
This is slow and prone to failure; see
https://github.com/aya-rs/aya/actions/runs/7204446013/job/19625908097.
=> .github: avoid homebrew automatic update

init/src/main.rs
```
warning: in a `match` scrutinee, avoid complex blocks or closures with blocks; instead, move the block or closure higher and bind it with a `let`
--> init/src/main.rs:127:23
|
127 |               match (|| {
|  _______________________^
128 | |                 let entry = entry.context("read_dir(/bin) failed")?;
129 | |                 let path = entry.path();
130 | |                 let status = std::process::Command::new(&path)
...   |
139 | |                 }
140 | |             })() {
| |_____________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#blocks_in_conditions
= note: `#[warn(clippy::blocks_in_conditions)]` on by default
```
https://github.com/rust-lang/rust-clippy/pull/11853 landed in nightly.
=> init: appease clippy

.github/workflows/ci.yml, aya/src/maps/ring_buf.rs, bpf/aya-bpf/src/maps/xdp/cpu_map.rs, bpf/aya-bpf/src/maps/xdp/dev_map.rs, bpf/aya-bpf/src/maps/xdp/dev_map_hash.rs, bpf/aya-bpf/src/maps/xdp/xsk_map.rs
Doctests aren't running in CI!
This PR:
1. Adds doctests to CI
2. Fixes ringbuf docs in aya
3. Fixes XDP map docs in aya-bpf
Fixes https://github.com/aya-rs/aya/issues/820
=> Fix docs build

aya/src/programs/tc.rs, aya/src/sys/netlink.rs, xtask/public-api/aya.txt
Similar to XdpLink::attach_to_link(), can be used to replace/upgrade the program attached to a link.
=> Add SchedClassifier::attach_to_link()

aya/src/lib.rs, bpf/aya-bpf/src/helpers.rs
=> Appease new nightly lints

xtask/public-api/aya.txt
`Send + Sync` became `Sync + Send` for reasons I don't understand.
=> public-api: regenerate

aya/src/bpf.rs, aya/src/sys/fake.rs
```
error: this call to `as_ref.map(...)` does nothing
--> aya/src/bpf.rs:536:30
|
536 |                 let btf_fd = btf_fd.as_ref().map(Arc::clone);
|                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `btf_fd.clone()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_asref
note: the lint level is defined here
--> aya/src/lib.rs:41:5
|
41  |     clippy::all,
|     ^^^^^^^^^^^
= note: `#[deny(clippy::useless_asref)]` implied by `#[deny(clippy::all)]`
error: could not compile `aya` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: initializer for `thread_local` value can be made `const`
--> aya/src/sys/fake.rs:14:61
|
14 |     pub(crate) static TEST_MMAP_RET: …
```
=> aya: appease new nightly clippy lints

bpf/aya-bpf/src/helpers.rs
This reverts commit 9861c1446efbd7303bf9485c864d5a00853368bd.
This no longer warns. See
https://github.com/rust-lang/rust/commit/d95d6ceecb372c66ed18a4e7a0bbb7.
=> Revert "bpf: appease nightly lint"

aya/src/programs/perf_event.rs, aya/src/sys/perf_event.rs, xtask/public-api/aya.txt
When inherit=true, processes spawned by the sampled processes get automatically sampled too.
=> aya: perf_event: add inherit argument to attach()

aya/src/maps/sock/sock_map.rs
Corrent an invalid transmutation for sock_map.
fd is already a ref of MapFd, so transmuting &fd to &SockMapFd is equivalent to transmuting &&SockMapFd into &SockMapFd which is buggy.
This simple program terminates in error with `Os error 9, invalid file descriptor`
```
let mut intercept_ingress: SockMap<_> = bpf.take_map("INTERCEPT_INGRESS").unwrap().try_into()?;
let map_fd = intercept_ingress.fd().try_clone()?;
```
SockHash is doing it correctly BTW https://github.com/aya-rs/aya/blob/main/aya/src/maps/sock/sock_hash.rs#L113
=> fix(aya-sock-map): invalid transmute when calling fd

.github/workflows/ci.yml, test/integration-test/build.rs, xtask/src/run.rs
This PR contains 3 commits to fix the macOS CI job which has been failing since ~12th February.
The causes was that Rust nightly updated to LLVM v18.1-RC2 but bpf-linker was linked against LLVM 17. Even with the bpf-linker v0.9.11 release (which supports the LLVM RC) macOS CI still fails due to LLVM 18.1-RC2 not being installable via `brew` to link against. Solving this with homebrew tap/bottles and/or binstalls of bpf-linker is the best long term solution. In the short term we revert to the last working rust nightly toolchain + bpf-linker v0.9.10
This was pretty hard to debug due to missing output from `cargo xtask integration-test`.
A commit in this PR provides a fix for that too which should make this easier to debug in future.
Note: At some point in CI we were also seeing errors about …
=> Fix macOS CI

Cargo.toml, aya-bpf-macros/Cargo.toml, aya-log-common/Cargo.toml, aya-log-ebpf-macros/Cargo.toml, aya-log-parser/Cargo.toml, aya-log/Cargo.toml, aya-obj/Cargo.toml, aya-tool/Cargo.toml, aya/Cargo.toml, bpf/aya-bpf-bindings/Cargo.toml, bpf/aya-bpf-cty/Cargo.toml, bpf/aya-bpf/Cargo.toml, bpf/aya-log-ebpf/Cargo.toml, init/Cargo.toml, test/integration-ebpf/Cargo.toml, test/integration-test/Cargo.toml, xtask/Cargo.toml
This allows for inheritance of common fields from the workspace root. The following fields have been made common:
- authors
- license
- repository
- homepage
- edition
=> chore: Use the cargo workspace package table

release.toml
post-release-commit-message was deprecated a while back.
=> chore: Fix release.toml

aya/BREAKING-CHANGES.md
This provides a `BREAKING-CHANGES.md` that we can populate per-crate. Doing so will allow us to pull this content into our changelog and websites to make things easier for users.
=> docs: Document breaking changes

.markdownlint-cli2.yaml, aya-obj/CHANGELOG.md, aya/CHANGELOG.md
This PR adds a generated changelog for aya and aya-obj.
This is generated from the git commit history.
=> Add Generated Changelogs for aya and aya-obj

aya-bpf-macros/src/cgroup_skb.rs
When no expected attach type is passed, the section name must be cgroup/skb not cgroup_skb.
Fixes #896
=> aya-bpf-macros: fix cgroup/skb section name

aya/LICENSE-APACHE, aya/LICENSE-MIT
This PR includes the licenses files in the crate workspace subdirectory.
Without this, they won't be showing on crates.io and would be giving out
errors on tooling such as rust2rpm.
Signed-off-by: Daniel Mellado <dmellado@redhat.com>
=> aya: include license in crate workspace

xtask/src/codegen/aya.rs, xtask/src/codegen/aya_ebpf_bindings.rs
Currently, when running `cargo +nightly xtask codegen` locally and in the codegen GHA workflow, an error occurs with only "Error: bindgen failed" displayed.
This was due to a path using "bpf/..." instead of "ebpf/...". It is now corrected to "ebpf", so the codegen command and GHA workflow shouldn't fail. Additionally, any bindgen fails should now display a more direct message on why it failed.
Fixes: #914
=> fix(xtask): corrected bpf to ebpf for path to aya-ebpf-bindings in codegen

.github/workflows/ci.yml
This fixes the current CI failures we're seeing on macos https://github.com/aya-rs/aya/actions/runs/8810405556/job/24182725423
The fix is to make sure bpf-linker is always rebuilt/relinked against the latest llvm installed via brew.
=> fix CI failures on macos

aya/src/sys/mod.rs
If a bpf syscall fails, it would be useful to know if this is due to not having enough permissions or that the kernel does not have BPF support.
Ubuntu kernels are compiled without `CONFIG_BPF_LIRC_MODE2` so this is important for https://github.com/seanyoung/cir/ : I would like to present a useful error saying your kernel does not support BPF IR decoders, go fix your kernel.
Also, when removing all BPF programs using `cir config --clear` then if there is no support for BPF, there is nothing to clear and the syscall error can be ignored.
=> Expose io_error in SyscallError

aya/Cargo.toml, aya/src/programs/uprobe.rs, xtask/public-api/aya.txt
This change enhances the logic for symbol lookup in uprobe or uretprobe. If the symbol is not found in the original binary, the search continues in the debug file associated through the debuglink section. Before searching the symbol table, it compares the build IDs of the two files. The symbol lookup will only be terminated if both build IDs exist and do not match. This modification does not affect the existing symbol lookup logic.
Refs: #936
=> aya: add symbol lookup in associated debug files

aya/src/lib.rs
```
warning: lint `pointer_structural_match` has been removed: converted into hard error, see RFC #3535 <https://rust-lang.github.io/rfcs/3535-constants-in-patterns.html> for more information
--> aya/src/lib.rs:57:5
|
57 |     pointer_structural_match,
|     ^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(renamed_and_removed_lints)]` on by default
```
=> Remove deny(pointer_structural_match)

.taplo.toml, aya/Cargo.toml
This fixes the current rustdoc build error by correcting the ordering of `rustdoc-args` to `-D warnings`. Additionally, this also removes the `recorder_arrays` field (defaults to false) so that the order is not modified, which is what caused the error in the first place. 😺
=> fix(docs): rustdoc flag correction to `-D warnings`

aya/src/util.rs
Currently `aya::maps::MapData::create` panics at [this line](https://github.com/aya-rs/aya/blob/c302f8370d34568df513a80036c3c5c44d41dad4/aya/src/util.rs#L133) when it is called on a custom / faulty Ubuntu kernel (tested with Proxmox VE 8.1.4).
The file `get_ubuntu_kernel_version` accesses contains only a new line on Proxmox VE 8.1.4 thus `get_ubuntu_kernel_version` returns a ParseError.
This PR changes the behaviour so that it will try the other options if there is a parse error.
=> fix(aya): Fix panic when creating map on custom ubuntu kernel

xtask/src/codegen/aya.rs, xtask/src/codegen/aya_ebpf_bindings.rs, xtask/src/codegen/mod.rs
This commit adds the s390x and powerpc architectures to codegen.
This will enable an upcoming PR to add support for aya to support theses architectures in both aya and aya-ebpf.
=> chore(xtask): Add s390x and powerpc64 to codegen

.github/workflows/gen.yml
Adds missing libelf headers that are now included
as part of libbpf-internal.h. Adds ppc64el and
s390x to the cross environment.
=> ci: Fix codegen and prep for s390/ppc64el

xtask/src/codegen/aya_ebpf_bindings.rs
If the bindings directory doesn't exist then create it.
=> chore(xtask): Create bindings dir

.github/workflows/ci.yml
6.1.0-15 seems to have been pulled.
=> Bump kernel image revision

ebpf/aya-ebpf/src/lib.rs, test/integration-ebpf/Cargo.toml, test/integration-ebpf/src/memmove_test.rs, test/integration-test/src/lib.rs, test/integration-test/src/tests/load.rs, xtask/public-api/aya-ebpf.txt
The compiler will emit this function for certain operations, but aya currently does not provide an implementation.
This leads to ebpf loading failures as the kernel can't find the symbol when loading the program.
The implementation is based on https://github.com/rust-lang/compiler-builtins/blob/master/src/mem/mod.rs#L29-L40 and https://github.com/rust-lang/compiler-builtins/blob/master/src/mem/impls.rs#L128-L135 Only the simplest case has been implemented, none of the word optimizations, since memcpy also doesn't seem to have them.
=> feat(aya-ebpf): Implement memmove

aya/src/programs/uprobe.rs
The variable fn_name was very much *not* the fn_name, but rather the object file path.
=> aya::programs::uprobe: fix bad variable name

xtask/src/codegen/aya.rs
Adds the `bpf_stats_type` enum to codegen bindings.
Refs: #959
=> codegen: add `bpf_stats_type` to codegen

aya/src/maps/ring_buf.rs
reverse-commit doesn't make sense. Should be `reserve` to match `bpf_ringbuf_reserve()`.
Reference: https://github.com/torvalds/linux/blob/master/Documentation/bpf/ringbuf.rst
=> docs(aya): fix typo

aya-log-common/src/lib.rs, aya-log/src/lib.rs, test/integration-ebpf/src/log.rs, test/integration-test/src/tests/log.rs, xtask/public-api/aya-log-common.txt
IP address types are available in `core`, so they can be used also in eBPF programs. This change adds support of these types in aya-log.
* Add implementation of `WriteTuBuf` to these types.
* Support these types in `Ipv4Formatter` and `Ipv6Formatter`.
* Support them with `DisplayHint::Ip`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/966)
=> aya-log: Allow logging `core::net::Ipv4Addr` and `core::net::Ipv6Addr`

.github/workflows/ci.yml
A naive attempt to resolve recent CI issues: `cargo: command not found`.
=> Fix CI on macOS

.github/workflows/ci.yml
The unversioned one is suffering from LLVM 19 => 20 migration issues, see llvm/llvm-project#100466.
=> ci: Use apt repository with LLVM 18 explicitly

aya/src/bpf.rs, aya/src/lib.rs, aya/src/maps/mod.rs, aya/src/maps/perf/perf_buffer.rs, aya/src/programs/cgroup_device.rs, aya/src/programs/extension.rs, aya/src/programs/links.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/mod.rs, aya/src/programs/perf_attach.rs, aya/src/programs/probe.rs, aya/src/sys/bpf.rs, aya/src/sys/netlink.rs, aya/src/sys/perf_event.rs
Rust 1.80 contains https://github.com/rust-lang/rust/pull/124210,
causing tests which we skip under miri to segfault.
=> Use MockableFd everywhere

aya/src/maps/bloom_filter.rs, aya/src/maps/lpm_trie.rs, aya/src/sys/bpf.rs, ebpf/aya-ebpf/src/maps/perf/perf_event_array.rs, ebpf/aya-ebpf/src/maps/perf/perf_event_byte_array.rs, xtask/public-api/aya-ebpf.txt
This brings Aya into compliance with libbpf and other popular loaders.
PerfEventArray sizes should be set to 0 at compile time.
At load time, they are set to the number of online CPUs.
Fixes: #995
=> Automatically Size PerfEventArrays

aya/src/maps/bloom_filter.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/sys/bpf.rs, xtask/public-api/aya.txt
There was a logic bug in the previously merged patch where we set the correctly calculated max_entries size with the original.
To fix this and prevent regressions a unit test was added. This highlighted that the original map definition needs to be mutated in order for the max_entries change to be properly applied.
As such, this resize logic moved out of aya::sys into aya::maps
=> fix(aya): Fix PerfEventArray resize logic

aya-log/src/lib.rs
Reverts aya-rs/aya#994. Upstream reverted dead_code changes.
=> Revert "Remove unused `allow(dead_code)`"

xtask/src/codegen/aya_ebpf_bindings.rs
Add tcx_action_base to pick up new TCX return codes, follow this pr up with a manual codegen actions run 
Relates to #918 and needed for #921
cc @dave-tucker
=> codegen: add `tcx_action_base` enum to bindings

.github/workflows/ci.yml, Cargo.toml
Ensure we run our integration tests against `linux-image-6.10.4-cloud-amd64-unsigned_6.10.4-1_amd64.deb` 
Bump xdpilone version to fix bug on latest kernel.
=> Add a 6.10 linux kernel to the virtualized testing in CI

aya/src/programs/raw_trace_point.rs, aya/src/programs/trace_point.rs, ebpf/aya-ebpf/src/helpers.rs
```
error: first doc comment paragraph is too long
--> aya/src/programs/raw_trace_point.rs:12:1
|
12 | / /// A program that can be attached at a pre-defined kernel trace point, but also
13 | | /// has an access to kernel internal arguments of trace points, which
14 | | /// differentiates them from traditional tracepoint eBPF programs.
15 | | ///
16 | | /// The kernel provides a set of pre-defined trace points that eBPF programs can
| |_
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#too_long_first_doc_paragraph
error: first doc comment paragraph is too long
--> ebpf/aya-ebpf/src/helpers.rs:1:1
|
1  | / //! This module contains kernel helper functions that may be exposed to specific BPF
2  | | //! program types. These helpers can be used …
```
=> Appease nightly clippy

aya/src/lib.rs, aya/src/programs/mod.rs, aya/src/sys/bpf.rs, aya/src/sys/mod.rs, test/integration-test/src/tests/smoke.rs, xtask/public-api/aya.txt
Checklist:
~~- [ ] Maybe? Add another util function for enabling runtime stats through sysctl procfs since `BPF_ENABLE_STATS` is a kernel 5.8+ feature.~~
These can be used for monitoring/benchmarking runtime statistics for programs. The `BPF_ENABLE_STATS` bpf command can be used in conjunction with `BPF_OBJ_GET_INFO_BY_FD` to monitor the `run_time_ns` & `run_cnt` fields.
More on it can be found in https://lore.kernel.org/bpf/20200430071506.1408910-2-songliubraving@fb.com/.
=> aya,aya-obj: expose run_time_ns & run_cnt fields, and add bpf_enable_stats util function

aya-log/src/lib.rs, aya-obj/src/lib.rs, aya-obj/src/links.rs, aya-obj/src/maps.rs, aya-obj/src/obj.rs, aya-obj/src/programs/mod.rs, aya-obj/src/programs/types.rs, aya/src/bpf.rs, aya/src/lib.rs, aya/src/maps/info.rs, aya/src/maps/mod.rs, aya/src/programs/info.rs, aya/src/programs/mod.rs, aya/src/sys/bpf.rs, aya/src/util.rs, test/integration-ebpf/Cargo.toml, test/integration-ebpf/src/map_test.rs, test/integration-ebpf/src/simple_prog.rs, test/integration-test/src/lib.rs, test/integration-test/src/tests.rs, test/integration-test/src/tests/info.rs, test/integration-test/src/tests/load.rs, test/integration-test/src/tests/smoke.rs, test/integration-test/src/utils.rs, xtask/public-api/aya-obj.txt, xtask/public-api/aya.txt
This adds support for the field availability in `ProgramInfo` and `MapInfo`.
Srry this is long, let me know and I can try to TL;DR it.
For `ProgramInfo`:
- Have `program_type()` to return `bpf_prog_type` instead of the integer representation.
- For fields that can't be `0`, return `Option<NonZero*>` type to indicate `None` as field being unavailable.
- Have `name_as_str()` use the `bpf_name()` feature probe as an additional check for whether field is available. Besides invalid unicode, `None` is returned if probe does not detect feature.
- For `mad_ids()`:
- Now returns a result of `Option<Vec<NonZeroU32>>`, with `None` indicating field is unavailable.
- On kernels below v4.15, the init closure that fills in the map info causes an `E2BIG` error since `check_uarg_tail_zero()` expects the …
=> aya,aya-obj,integration-test: add better support in `ProgramInfo` & `MapInfo` for old kernels

xtask/src/codegen/aya.rs
Adds the `bpf_perf_event_type` enum to Rust FFI bindings.
This enum is used in `perf_event.type` field in `bpf_link_info` (https://elixir.bootlin.com/linux/v6.6/source/include/uapi/linux/bpf.h#L6530).
I plan to use it in another PR (coming soon) that implements `LinkInfo` for `bpf_link_info`.
=> codegen: add `bpf_perf_event_type` enum bindings

aya/src/programs/cgroup_device.rs, aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/cgroup_sysctl.rs, aya/src/programs/links.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/mod.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/sock_ops.rs, aya/src/sys/bpf.rs, xtask/public-api/aya.txt
Add the option to support multiple and overrideable programs per cgroup
This change allows multiple BPF programs to attach to a cgroup (via the option
`CgroupAttachMode::AllowMultiple`), and allows a program to specify that it can be
overridden by one in a sub-cgroup (via the option `CgroupAttachMode::AllowOverride`).
=> Add the option to support multiple and overrideable programs per cgroup

ebpf/aya-ebpf/src/programs/sock_ops.rs, xtask/public-api/aya-ebpf.txt
A sock_ops program should always return 1 on success, otherwise [`__cgroup_bpf_run_filter_sock_ops()`](https://github.com/torvalds/linux/commit/40304b2a1567fecc321f640ee4239556dd0f3ee0#diff-c3fa9a9d1fb31882db807c25992de189916efb3439621ccd625dcf22a8c953bf) would return `-EPERM`.
The reply fields of the `bpf_sock_ops` struct are there in case a bpf program needs to return a value. For example, [BPF_SOCK_OPS_TIMEOUT_INIT](https://github.com/torvalds/linux/commit/8550f328f45db6d37981eb2041bc465810245c03) and [BPF_SOCK_OPS_RWND_INIT](https://github.com/torvalds/linux/commit/13d3b1ebe28762c79e981931a41914fae5d04386) are invoked via [`tcp_call_bpf()`](https://github.com/torvalds/linux/commit/40304b2a1567fecc321f640ee4239556dd0f3ee0#diff-ff57716b18eaf625ed142c9cb45d80319f37663be3c35ef3001de8f61473 …
=> aya-ebpf: Add set_reply accessor to SockOpsContext

aya-log/src/lib.rs, aya/src/maps/info.rs, aya/src/maps/mod.rs, aya/src/programs/info.rs, test/integration-test/src/tests/info.rs, test/integration-test/src/tests/load.rs, xtask/public-api/aya.txt
Addresses the feedback from #1007: 🙃
- Remove panic from `unwrap` and `expect`
- `Option<NonZero*>` => `Option<int>` with `0` mapping to `None`
~- Use `aya_ebpf::binding` in `u32` conversion in prog, link, and attach type for more straightforward matching. The `::Type` appears to be an alias for `u32`, so cast wasn't required.~ see comment
=> aya: remove `unwrap`/`expect` and `NonZero*` in info

.github/workflows/ci.yml
This updates the linux kernels of the CI linux runners since at least one of the current ones has become unavailable as seem in this build https://github.com/aya-rs/aya/actions/runs/10843802034/job/30091556395
=> Fix linux kernel version in gh ci runners

test/integration-ebpf/src/redirect.rs, test/integration-ebpf/src/relocations.rs, test/integration-test/src/tests/rbpf.rs
Made stricter in https://github.com/rust-lang/rust/commit/5ba6db1b648d9.
I'm pretty sure our doctests still contain patterns that offend this lint but I couldn't figure out how to make them complain.
=> Appease `static_mut_refs`

.github/workflows/ci.yml
Instead of relying on Homebrew for macOS (which ships older LLVM
versions) and `apt.llvm.org` for Linux (which often has bugs at the
packaging level), we now use the tarball from Rust CI to provide
`libLLVM`. This ensures it always matches the version used by the latest
Rust nightly.
This removes our reliance on homebrew shipping LLVM versions matching
those used by rustc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1022)
=> ci: Use libLLVM from Rust CI tarball

aya-log/src/lib.rs, xtask/public-api/aya-log.txt
Otherwise you cannot distinguish `&[1u8, 0u8]` from `&[0x10u8]` (they both become `10`)
=> fix(aya-log): print &[u8] using full width

aya-obj/include/linux_wrapper.h, xtask/src/codegen/aya.rs
Adds the following to codegen:
- `bpf_cgroup_iter_order`: used in `bpf_link_info.iter.group.order`
- `NFPROTO_*`: used in `bpf_link_info.netfilter.pf`
- `nf_inet_hooks`: used in `bpf_link_info.netfilter.hooknum`
`linux/netfilter.h` is included in `aya-obj/include/linux_wrapper.h` for `NFPROTO_.*` and `nf_inet_hooks` to generate.
This is all that's left for `bpf_link_info`. 🙃
=> codegen: add `bpfcgroup_iter_order` `NFPROTO*` `nf_inet_hooks`

Cargo.toml, test/integration-test/Cargo.toml
Doesn't make much sense to have them here.
=> Remove workspace members from workspace.dependencies

.github/workflows/ci.yml, xtask/src/run.rs
I did this for arm64 because we'd get a black screen without it but I
have now confirmed that console=ttyAMA0 solves that problem.
I don't remember why I did it for x86.
=> qemu: remove bios argument

ebpf/aya-ebpf/src/helpers.rs, test/integration-ebpf/Cargo.toml, test/integration-ebpf/src/strncmp.rs, test/integration-test/src/lib.rs, test/integration-test/src/tests.rs, test/integration-test/src/tests/strncmp.rs, xtask/public-api/aya-ebpf.txt
The `bpf_strncmp` helper allows for better string comparison in eBPF programs.
Kernel patchset:
https://lore.kernel.org/bpf/20211210141652.877186-1-houtao1@huawei.com/
=> bpf: Add `bpf_strncmp` helper

aya/src/bpf.rs, aya/src/maps/mod.rs, xtask/public-api/aya.txt
fix #1081 
the proposed solution is to remove the warning log and instead provide more meaningful information directly within the error itself.
without considering the issue, right now we have just a warning log (which contains the important information), but this is misleading since it actually leads to an error. I believe this can cause confusion because the critical details should be part of the error itself. For this reason I consolidated all the relevant information into the error message.
Additionally, I updated the `map_type` field type in `Unsupported` error from`u32` to `bpf_map_type`, as an unsupported map has a specific map type, which is distinct from a generic `u32` used in cases like the `InvalidMapType` error.
PS: Regarding `InvalidMapType` and other map-related errors, I …
=> fix unsupported maps warning message

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Aya Guru](https://gurubase.io/g/aya) to Gurubase. Aya Guru uses the data from this repo and data from the [docs](https://aya-rs.dev/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Aya Guru", which highlights that Aya now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable Aya Guru in …
=> Introducing Aya Guru on Gurubase.io

Cargo.toml
`0.2.164` and `0.2.165` are affected by rust-lang/libc#4149. Pin the last working version until a proper fix is released.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1097)
=> chore: Pin `libc` to `0.2.163`

Cargo.toml
Reverts aya-rs/aya#1097.
The bad version (0.2.165) has been yanked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1099)
=> Revert "chore: Pin `libc` to `0.2.163`"

Cargo.toml, aya-build/Cargo.toml, aya-build/src/lib.rs, test/integration-test/Cargo.toml, test/integration-test/build.rs, xtask/public-api/aya-build.txt
Please ignore all but the last commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1101)
=> Extract aya-build for building eBPF crates

aya-ebpf-macros/Cargo.toml
The presence of this version specification causes cargo-smart-release to
trip on the circular dependency.
Fixes #1050.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1106)
=> aya-ebpf-macros: remove aya-ebpf version

.github/scripts/download_kernel_images.sh, .github/workflows/ci.yml, test/README.md, xtask/src/run.rs
See commit message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1114)
=> ci: cache downloads

aya/src/bpf.rs, aya/src/maps/bloom_filter.rs, aya/src/maps/hash_map/hash_map.rs, aya/src/maps/lpm_trie.rs, aya/src/maps/mod.rs, aya/src/programs/uprobe.rs, aya/src/sys/bpf.rs, aya/src/sys/fake.rs, aya/src/sys/mod.rs, aya/src/sys/perf_event.rs, xtask/public-api/aya.txt
Use native C types to avoid platform-dependent conversions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1123)
=> Avoid useless conversions

aya/src/bpf.rs
This macro is required if you are bundling programs statically into your binary, which is not an uncommon thing to do.
This change updates the documentation for the load function to mention this macro and the need for alignment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1119)
=> docs: update docs for load to mention include_bytes_aligned

.github/scripts/download_kernel_images.sh
Seems 6.10 is now being marked `+bpo`.
Improve error handling while I'm here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1127)
=> Allow `+bpo` kernels

aya-tool/src/bindgen.rs
Closes #1128.
cc @cppcoffee would you mind testing?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1129)
=> aya-tool: enable clang_macro_fallback

ebpf/aya-ebpf/src/args.rs, ebpf/aya-ebpf/src/lib.rs, ebpf/aya-ebpf/src/programs/raw_tracepoint.rs, test/integration-common/src/lib.rs, test/integration-ebpf/Cargo.toml, test/integration-ebpf/src/raw_tracepoint.rs, test/integration-test/src/lib.rs, test/integration-test/src/tests.rs, test/integration-test/src/tests/raw_tracepoint.rs, xtask/public-api/aya-ebpf.txt
Provide an `arg()` method in `RawTracepointArgs` wrapper of `bpf_raw_tracepoint_args` and also in `RawTracepointContext`, so it's directly available in raw tracepoint programs.
The methods and traits implemented here are unsafe. There is no way to reliably check the number of available arguments, so requesting a non-existing one leads to undefined behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/805)
=> bpf: Handle raw tracepoint arguments

ebpf/aya-ebpf-bindings/build.rs, ebpf/aya-ebpf-cty/build.rs, ebpf/aya-ebpf/build.rs
bpf_target_arch should be riscv64, but target triple starts with riscv64gc (and possibly riscv64 followed by any combination of extensions).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1139)
=> Fix aya-ebpf-* riscv64 build

aya-tool/src/lib.rs, xtask/src/codegen/aya.rs, xtask/src/codegen/aya_ebpf_bindings.rs, xtask/src/codegen/mod.rs
This will generate bindings for mips the next time that the codegen job is run.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1150)
=> chore(xtask): Add mips to codegen

xtask/src/codegen/aya.rs, xtask/src/codegen/aya_ebpf_bindings.rs
Per the comment added in the code, there are 2 definitions of BPF_F_LINK in the kernel headers. Once is in an anonymous enum which bindgen will constify, and once is via a #define macro. The values are identical. The fix is to exclude BPF_F_LINK from the list of variables in bindgen removing one of the duplicate definitions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1154)
=> chore(codegen): Fix duplicate BPF_F_LINK

.cargo/config.toml, .github/workflows/ci.yml, Cargo.toml, aya-obj/src/generated/mod.rs, ebpf/aya-ebpf-bindings/build.rs, ebpf/aya-ebpf-bindings/src/lib.rs, ebpf/aya-ebpf-bindings/src/mips/mod.rs, ebpf/aya-ebpf-cty/build.rs, ebpf/aya-ebpf-cty/src/lib.rs, ebpf/aya-ebpf/build.rs, ebpf/aya-ebpf/src/args.rs, ebpf/aya-ebpf/src/programs/probe.rs, ebpf/aya-ebpf/src/programs/retprobe.rs
This commit updates xtask scripts to generated bindings for MIPS alongside other architectures. It also updates
`aya-obj/src/generated/mod.rs` and `bpf/aya-bpf-bindings/src/lib.rs` to use the mips bindings.
<details>
<summary> Integration Tests using libbpf v1.1.0</summary>
```rust
emerald :: hobby/dhcp_aya/aya 130 » RUST_LOG=trace cargo xtask integration-test --libbpf-dir ./libbpf/
Finished dev [unoptimized + debuginfo] target(s) in 0.16s
Running `target/debug/xtask integration-test --libbpf-dir ./libbpf/`
Fresh unicode-ident v1.0.6
Fresh core v0.0.0 (/home/ishan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
Fresh proc-macro2 v1.0.49
Fresh rustc-std-workspace-core v1.99.0 (/home/ishan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/ …
```
=> Added MIPS bindings

xtask/src/codegen/aya.rs
This is required for nicer netlink error messages
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1156)
=> chore(codegen): Add nlmsgerr_attrs

aya/src/programs/mod.rs, aya/src/programs/tc.rs, aya/src/programs/xdp.rs, aya/src/sys/netlink.rs, xtask/public-api/aya.txt
This returns error strings from netlink since they are more informative than the raw os error. For example:
"Device or Resource Busy" vs. "XDP program already attached".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/690)
=> aya: Return error messages from netlink

aya-obj/src/obj.rs, aya/src/bpf.rs, aya/src/sys/bpf.rs
See individual commits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1165)
=> Remove duplication, avoid handwritten assembly

.github/workflows/ci.yml, .github/workflows/gen.yml, aya-obj/include/linux_wrapper.h, aya-tool/src/generate.rs, aya/src/bpf.rs, aya/src/maps/perf/perf_buffer.rs, aya/src/programs/perf_attach.rs, aya/src/sys/mod.rs, aya/src/sys/perf_event.rs, ebpf/aya-ebpf-bindings/include/bindings.h, xtask/src/codegen/aya.rs, xtask/src/codegen/aya_ebpf_bindings.rs, xtask/src/codegen/mod.rs
We already use this for the lint job on main.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1168)
=> gen: use peter-evans/create-pull-request@v7

aya/src/maps/hash_map/per_cpu_hash_map.rs, aya/src/sys/bpf.rs, aya/src/util.rs
PerCpuHashMap was never returning MapError::KeyNotFound because
bpf_map_lookup_elem_per_cpu was replacing Ok(None) with Ok(Some(zeroed_value)).
Update bpf_map_lookup_elem_per_cpu to map the Option value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1182)
=> aya: Fix PerCpuHashMap NotFound

.github/workflows/gen.yml
ubuntu-20.04 is being deprecated.
See https://github.com/actions/runner-images/issues/11101.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1188)
=> gen: run on ubuntu-latest

test/integration-test/build.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1143)
=> integration-test: allow llvm-objcopy env override

ebpf/aya-ebpf/src/lib.rs, ebpf/aya-ebpf/src/maps/array.rs, ebpf/aya-ebpf/src/maps/hash_map.rs, ebpf/aya-ebpf/src/maps/lpm_trie.rs, ebpf/aya-ebpf/src/maps/per_cpu_array.rs, ebpf/aya-ebpf/src/maps/sock_hash.rs, ebpf/aya-ebpf/src/maps/sock_map.rs, ebpf/aya-ebpf/src/maps/xdp/dev_map.rs, ebpf/aya-ebpf/src/maps/xdp/dev_map_hash.rs, ebpf/aya-ebpf/src/maps/xdp/xsk_map.rs, xtask/public-api/aya-ebpf.txt
Add `set()` function for `Array<T>`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1005)
=> feat: Add `set` for `Array<T>`

ebpf/aya-ebpf/src/programs/xdp.rs, xtask/public-api/aya-ebpf.txt
This change exposes the ifindex field from the underlying xdp_md data structure to the XdpContext in Aya. The ifindex represents the unique OS-provided index for a network interface.
Fixes #1140
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1141)
=> aya-ebpf: add ifindex support to XdpContext

.github/workflows/ci.yml, aya/src/maps/mod.rs, aya/src/programs/cgroup_device.rs, aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/cgroup_sysctl.rs, aya/src/programs/mod.rs, aya/src/programs/probe.rs, aya/src/programs/sock_ops.rs, aya/src/programs/tc.rs, aya/src/programs/xdp.rs, aya/src/sys/bpf.rs, aya/src/util.rs
Cache the current kernel version in a thread-local while I'm here.
Closes https://github.com/aya-rs/aya/issues/1024.
Closes https://github.com/aya-rs/aya/pull/1042.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1196)
=> aya: remove panics on indeterminate kernel version

.github/workflows/gen.yml, xtask/src/codegen/aya.rs, xtask/src/codegen/aya_ebpf_bindings.rs, xtask/src/codegen/mod.rs
This patch adds binding generation support for the Rust Tier 2 targets `loongarch64-unknown-linux-*`. I will send subsequent patches to enable full support once the binding files are generated. Thanks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1197)
=> chore(xtask): Add loongarch64 to codegen

aya/src/maps/xdp/xsk_map.rs, test/integration-test/src/tests/xdp.rs, xtask/public-api/aya.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/848)
=> aya: Add `XskMap::unset`

aya/src/bpf.rs, aya/src/programs/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1211)
=> programs: allow program names to be static strings

.mergify.yml
Merging via comment isn't possible. We could merge this automatically on green, however we'd prefer to use @dependabot merge or merge manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1210)
=> chore: Disable mergify on dependabot PRs

aya/src/sys/bpf.rs, test/integration-ebpf/src/map_test.rs
Limit of map names in eBPF is 16 bytes and they have to be NULL terminated.
Before this change, long names were truncated to 16 bytes. `MAP_WITH_LOOOONG_NAAAAAAAAME` would become `MAP_WITH_LOOOONG`, which doesn't contain the NULL byte.
This change fixes that by truncating the name to 15 bytes, ensuring that the 16th byte is NULL. `MAP_WITH_LOOOONG_NAAAAAAAAME` is truncated to `MAP_WITH_LOOOON\0`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1216)
=> aya: Ensure that truncated map names are NULL terminated

Cargo.toml, aya-log/src/lib.rs, aya-obj/src/btf/btf.rs, aya-obj/src/btf/info.rs, aya-obj/src/btf/relocation.rs, aya-obj/src/btf/types.rs, aya-obj/src/obj.rs, aya-obj/src/relocation.rs, aya-tool/src/generate.rs, aya/src/maps/perf/perf_event_array.rs, aya/src/maps/xdp/cpu_map.rs, aya/src/maps/xdp/dev_map.rs, aya/src/maps/xdp/dev_map_hash.rs, aya/src/maps/xdp/xsk_map.rs, aya/src/programs/probe.rs, aya/src/programs/socket_filter.rs, aya/src/programs/uprobe.rs, aya/src/programs/utils.rs, ebpf/aya-ebpf/src/maps/sock_hash.rs, ebpf/aya-ebpf/src/maps/sock_map.rs, test/integration-ebpf/src/uprobe_cookie.rs, test/integration-test/src/tests/elf.rs, test/integration-test/src/tests/iter.rs, test/integration-test/src/tests/xdp.rs, xtask/src/codegen/aya_ebpf_bindings.rs, xtask/src/codegen/helpers.rs
We have previously tried to import traits anonymously where possible but enforcing this manually was hard.
Since Rust 1.83 clippy can now enforce this for us.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1224)
=> chore(*): set clippy unused_trait_names = warn

aya/src/bpf.rs, aya/src/programs/cgroup_device.rs, aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/cgroup_sockopt.rs, aya/src/programs/cgroup_sysctl.rs, aya/src/programs/extension.rs, aya/src/programs/fentry.rs, aya/src/programs/fexit.rs, aya/src/programs/flow_dissector.rs, aya/src/programs/iter.rs, aya/src/programs/kprobe.rs, aya/src/programs/lirc_mode2.rs, aya/src/programs/lsm.rs, aya/src/programs/mod.rs, aya/src/programs/perf_event.rs, aya/src/programs/raw_trace_point.rs, aya/src/programs/sk_lookup.rs, aya/src/programs/sk_msg.rs, aya/src/programs/sk_skb.rs, aya/src/programs/sock_ops.rs, aya/src/programs/socket_filter.rs, aya/src/programs/tc.rs, aya/src/programs/tp_btf.rs, aya/src/programs/trace_point.rs, aya/src/programs/uprobe.rs, aya/src/programs/xdp.rs, test/integration-test/src/tests/info.rs, xtask/public-api/aya.txt
Allow for a ProgramInfo to be converted into one of the program types that we support. This allows for a user of Aya access to reattach, pin or unload a program that was either, previously loaded, or was loaded by another process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1209)
=> feat: Allow conversions to Program from ProgramInfo

Cargo.toml, clippy.sh, ebpf-panic/Cargo.toml, ebpf-panic/src/lib.rs, test/integration-ebpf/Cargo.toml, test/integration-ebpf/src/bpf_probe_read.rs, test/integration-ebpf/src/log.rs, test/integration-ebpf/src/map_test.rs, test/integration-ebpf/src/memmove_test.rs, test/integration-ebpf/src/name_test.rs, test/integration-ebpf/src/pass.rs, test/integration-ebpf/src/raw_tracepoint.rs, test/integration-ebpf/src/redirect.rs, test/integration-ebpf/src/relocations.rs, test/integration-ebpf/src/ring_buf.rs, test/integration-ebpf/src/simple_prog.rs, test/integration-ebpf/src/strncmp.rs, test/integration-ebpf/src/tcx.rs, test/integration-ebpf/src/test.rs, test/integration-ebpf/src/two_progs.rs, test/integration-ebpf/src/uprobe_cookie.rs, test/integration-ebpf/src/xdp_sec.rs
Working with aya in vscode will currently show a number of warnings along the lines of:
```
found duplicate lang item `panic_impl`
the lang item is first defined in crate `std` (which `aya` depends on)
...
second definition in the local crate (`bpf_probe_read`)
```
This comes from feature unification.
integration-test requires the integration-common user feature, which requires aya, which in turn brings in std.
For this same reason we avoid running clippy across the whole workspace.
We can avoid this issue by using the panic handler from the panic_halt crate, which implements the same loop {} panic handler we use today.
However, it seems rustc is happy to conditionally link the panic handler from an external crate without issuing warnings.
- - -
This change is [<img …
=> chore: Fix clippy panic_handler warnings

aya/src/sys/bpf.rs
In aarch64, with kernel 5.5, my programs that use `bpf_probe_read_user` don't work successfully because `aya` is mistakenly re-writting it `bpf_probe_read` because it falsely detects that the kernel doesn't support `bpf_probe_read_user`.
I hadn't updated my `aya` version in a while, but while updating it to fix a separate issue (panics when parsing kernel versions of PVE kernels) and running my test suite I saw tests failing on aarch64 5.5 kernels. A git bisect led me to this commit: https://github.com/aya-rs/aya/commit/942ea51906fea4e3152e1bd3ef5832bc0df5b205 and further investigation in the difference of the new and old assembly showed that the only difference was subtracting 8 vs adding -8. When I put it back as adding 8 (but without handwritten assembly) then things work as expected. …
=> aya: fix is_probe_read_kernel_supported in aarch64 kernels 5.5

aya/src/sys/bpf.rs
We should use the generated one, not the one provided by the libc crate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1240)
=> chore(aya): Use BPF_ADD from bindings

Cargo.toml
https://github.com/rust-random/getrandom/releases/tag/v0.3.2 contains
https://github.com/rust-random/getrandom/commit/b75db5cede302bc9734f5bf2b9048a6e05c7f11e.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1242)
=> Remove getrandom patch

.github/scripts/download_kernel_images.sh, .github/scripts/find_kernels.py, .github/workflows/ci.yml, Cargo.toml, test-distro/Cargo.toml, test-distro/src/depmod.rs, test-distro/src/lib.rs, test-distro/src/modprobe.rs, xtask/Cargo.toml, xtask/src/run.rs
- **Remove stale comments**
- **Use nul bytes as delimiters**
- **Revert "ci: download gen_init_cpio with authentication"**
- **test-distro: extract common decompression code**
- **test-distro: reduce indentation**
- **test-distro: build without cross toolchain**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1243)
=> clippy: allow running without cross toolchain

.github/workflows/ci.yml
6.12 is an LTS kernel, while 6.10 is not. The latter has reached EOL and
no longer lives on debian mirrors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1249)
=> ci: test against 6.12 rather than 6.10

aya/src/programs/links.rs, aya/src/programs/mod.rs, test/integration-test/src/tests/load.rs, xtask/public-api/aya.txt
We have had loaded_links in the API as `#[doc(hidden)]` for a while. I've been using it in bpfman and it's been fine. This commit does the minimal work required to make the API stable.
We expose a `LinkInfo` type - similar to `ProgInfo` - which wraps the generated type. In this case, `bpf_link_info`.
A few accessor functions have been added for `id`, `link_type` and `program_id`. There are many more fields that could be (eventually) made public.
As a convenience, `LinkInfo` can be retrieved from an existing FdLink by using `FdLink::info()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1262)
=> feat(aya): Make LinkInfo and loaded_links public

Cargo.toml, aya-obj/src/obj.rs, aya/src/bpf.rs, aya/src/programs/info.rs, aya/src/sys/bpf.rs, aya/src/sys/feature_probe.rs, aya/src/sys/mod.rs, test/integration-test/Cargo.toml, test/integration-test/src/tests.rs, test/integration-test/src/tests/feature_probe.rs, test/integration-test/src/tests/info.rs, test/integration-test/src/tests/load.rs, xtask/public-api/aya-obj.txt, xtask/public-api/aya.txt
I tested the new integration tests against a ton of ubuntu mainline kernels. Basically on every version where the program/map type was introduced I was able to verify that they were passing as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1063)
=> aya: add feature probing for program and map type

aya/src/programs/cgroup_skb.rs, aya/src/programs/cgroup_sock.rs, aya/src/programs/cgroup_sock_addr.rs, aya/src/programs/iter.rs, aya/src/programs/kprobe.rs, aya/src/programs/links.rs, aya/src/programs/perf_attach.rs, aya/src/programs/perf_event.rs, aya/src/programs/sock_ops.rs, aya/src/programs/tc.rs, aya/src/programs/trace_point.rs, aya/src/programs/uprobe.rs, aya/src/programs/xdp.rs, xtask/public-api/aya.txt
Implements TryFrom for FdLink for CgroupSkb, CgroupSock, CgroupSockAddr and SockOps program types. This allows support for link pinning for these program types, aligning with the [documentation for FdLink.](https://github.com/aya-rs/aya/blob/main/aya/src/programs/links.rs#L110)
Fixes: #739
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1264)
=> aya: implement TryFrom<[Program Type]> for FdLink for various program types

test/integration-test/src/tests/bpf_probe_read.rs, test/integration-test/src/tests/btf_relocations.rs, test/integration-test/src/tests/elf.rs, test/integration-test/src/tests/feature_probe.rs, test/integration-test/src/tests/info.rs, test/integration-test/src/tests/iter.rs, test/integration-test/src/tests/load.rs, test/integration-test/src/tests/log.rs, test/integration-test/src/tests/raw_tracepoint.rs, test/integration-test/src/tests/rbpf.rs, test/integration-test/src/tests/relocations.rs, test/integration-test/src/tests/ring_buf.rs, test/integration-test/src/tests/smoke.rs, test/integration-test/src/tests/strncmp.rs, test/integration-test/src/tests/tcx.rs, test/integration-test/src/tests/uprobe_cookie.rs, test/integration-test/src/tests/xdp.rs
Use the fully qualified macro name which composes better with
`test_case` and makes it easier to spot cases where it is missing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1290)
=> integration-test: add missing `test_log` decorator

.github/workflows/ci.yml
We've recently added an xtask to bpf-linker (aya-rs/bpf-linker#282), which resulted in multiple binary targets. Therefore, bpf-linker has to be installed with the following command:
```
cargo install --git https://github.com/aya-rs/bpf-linker.git bpf-linker
```
The last argument (`bpf-linker`) specifies the binary target.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1295)
=> ci: Fix bpf-linker installation

aya-log/src/lib.rs
The `Format` implementations for various types were using a wildcard `_` to match the `None` case on `Option<DisplayHint>`.
This is incorrect as it would also match any `Some(...)` variants that were not explicitly handled, leading to unexpected behavior.
This commit changes the wildcard `_` to an explicit `None` match to ensure that only the `None` case is handled, making the matching more explicit and correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1300)
=> aya-log: Use `None` instead of wildcard in `Format` impls

ebpf/aya-log-ebpf/src/lib.rs, test/integration-ebpf/src/log.rs, test/integration-test/src/tests/log.rs
#1335 was incomplete as the static variable was declared mut, putting it into a section that the verifier considers mutable and thus breaking the check. This change simply unmarks it `mut` and adds a corresponding test which should fail if the verifier does not recognise that the loop is not executed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1337)
=> Do not make the static mut to prevent verification failure

aya-log-ebpf-macros/src/expand.rs, test/integration-ebpf/src/log.rs
This is load-bearing in aya-template.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1339)
=> aya-log-ebpf: allow macros in expr position

aya-log-common/src/lib.rs, aya-log-ebpf-macros/src/expand.rs, aya-log/src/lib.rs, ebpf/aya-ebpf/src/maps/ring_buf.rs, ebpf/aya-log-ebpf/src/lib.rs, test/integration-common/src/lib.rs, test/integration-ebpf/src/log.rs, test/integration-test/src/tests/log.rs, xtask/public-api/aya-ebpf.txt, xtask/public-api/aya-log-common.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1294)
=> aya-log: make logging zero-copy

aya-ebpf-macros/src/btf_map.rs, aya-ebpf-macros/src/lib.rs, aya-obj/src/btf/btf.rs, aya-obj/src/obj.rs, ebpf/aya-ebpf/src/btf_maps/array.rs, ebpf/aya-ebpf/src/btf_maps/mod.rs, ebpf/aya-ebpf/src/lib.rs, ebpf/aya-ebpf/src/maps/array.rs, ebpf/aya-ebpf/src/maps/hash_map.rs, ebpf/aya-ebpf/src/maps/lpm_trie.rs, ebpf/aya-ebpf/src/maps/per_cpu_array.rs, ebpf/aya-ebpf/src/maps/sock_hash.rs, ebpf/aya-ebpf/src/maps/sock_map.rs, ebpf/aya-ebpf/src/maps/xdp/dev_map.rs, ebpf/aya-ebpf/src/maps/xdp/dev_map_hash.rs, ebpf/aya-ebpf/src/maps/xdp/xsk_map.rs, test/integration-common/src/lib.rs, test/integration-ebpf/Cargo.toml, test/integration-ebpf/src/array.rs, test/integration-test/src/lib.rs, test/integration-test/src/tests.rs, test/integration-test/src/tests/array.rs, xtask/public-api/aya-ebpf-macros.txt, xtask/public-api/aya-ebpf.txt, xtask/public-api/aya-obj.txt
Before this change, Aya supported only legacy BPF map definitions, which are instances of the `bpf_map_def` struct and end up in the `maps` ELF section.
This change introduces a BTF map definition for arrays, with custom structs indicating the metadata of the map, which end up in the `.maps` section.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1340)
=> aya-ebpf: Add BTF array definition

aya-log-common/src/lib.rs, clippy.sh, ebpf/aya-ebpf-bindings/src/lib.rs, ebpf/aya-ebpf/build.rs, ebpf/aya-ebpf/src/lib.rs, ebpf/aya-log-ebpf/Cargo.toml, ebpf/aya-log-ebpf/src/lib.rs
This build warnings from integration tests and makes `aya-ebpf`'s build
script stricter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1361)
=> ebpf: run clippy with target=bpf
