- aya/src/bpf.rs
- aya/src/obj/mod.rs
- aya/src/programs/lirc_mode2.rs
- aya/src/programs/mod.rs
> Add support for lirc programs

- .github/workflows/build-test.yml
- aya/src/maps/perf/async_perf_event_array.rs
- aya/src/programs/lirc_mode2.rs
Signed-off-by: Sean Young <sean@mess.org>
> Fix doctest and run them during CI

- aya/src/maps/array/array.rs
- aya/src/maps/array/per_cpu_array.rs
- aya/src/maps/array/program_array.rs
- aya/src/maps/hash_map/hash_map.rs
- aya/src/maps/hash_map/per_cpu_hash_map.rs
- aya/src/maps/perf/async_perf_event_array.rs
- aya/src/maps/perf/perf_event_array.rs
- aya/src/maps/queue.rs
- aya/src/maps/sock/sock_hash.rs
- aya/src/maps/sock/sock_map.rs
- aya/src/maps/stack.rs
- aya/src/maps/stack_trace.rs
- aya/src/programs/cgroup_skb.rs
- aya/src/programs/kprobe.rs
- aya/src/programs/lirc_mode2.rs
- aya/src/programs/sk_msg.rs
- aya/src/programs/sk_skb.rs
- aya/src/programs/sock_ops.rs
- aya/src/programs/socket_filter.rs
- aya/src/programs/tc.rs
- aya/src/programs/trace_point.rs
- aya/src/programs/xdp.rs
> aya: add minimum kernel version for each map and program tyoes

- bpf/aya-bpf-macros/src/expand.rs
- bpf/aya-bpf-macros/src/lib.rs
- bpf/aya-bpf/src/maps/hash_map.rs
- bpf/aya-bpf/src/programs/mod.rs
- bpf/aya-bpf/src/programs/tracepoint.rs
This patch add initial support for tracepoint program type.
Hope you enjoy.
Signed-off-by: Tw <wei.tan@intel.com>
> bpf: add support for tracepoint program

- README.md
> README: Add docs link

- aya/src/obj/btf/btf.rs
- aya/src/obj/btf/types.rs
> btf: Add bindings for BTF_KIND_FLOAT

- aya/Cargo.toml
- aya/src/programs/uprobe.rs
> bump obj to 0.26

- .github/workflows/build-aya-bpf.yml
- .github/workflows/build-aya.yml
- .github/workflows/lint.yml
- bpf/aya-bpf-bindings/build.rs
- bpf/aya-bpf-cty/build.rs
> ci: Add CI for aya-bpf

- aya/src/obj/mod.rs
`section.data.len()` is always 0 for `.bss`, so use `section.size()` instead to determine section length. Fixes #88
> aya/obj: fix incorrect section size for .bss

- aya/src/obj/mod.rs
This commit fixes name parsing of sk_skb sections such that both named
and unnamed variants will work correctly.
Before this patch, a section named `sk_skb/stream_parser` would result in an error
> obj: fix name parsing for sk_skb sections

- bpf/aya-bpf-macros/src/expand.rs
- bpf/aya-bpf-macros/src/lib.rs
This commit adds the stream_parser and stream_verdict macros for use in
bpf programs
> bpf: Add macros for sk_skb programs

- bpf/aya-bpf-macros/src/expand.rs
- bpf/aya-bpf-macros/src/lib.rs
> bpf: Add macro for socket_filter programs

- aya/src/sys/mod.rs
i donnot know if this is the best way of removing the warnings, maybe #[cfg(allow ...)] is a better idea? I'd love to do this job for this project.
> update some cfgs to get rid of the annoying warnings

- aya/src/obj/btf/relocation.rs
Use `ProgramSection` to extract the correct program name from the ELF section name when performing BTF relocations. This fixes a relocation failure when relocating tracepoints in a section named `tracepoint/<category>/name`.
> aya: use correct program name when relocating

- bpf/aya-bpf/src/maps/array.rs
- bpf/aya-bpf/src/maps/hash_map.rs
- bpf/aya-bpf/src/maps/per_cpu_array.rs
- bpf/aya-bpf/src/maps/queue.rs
- bpf/aya-bpf/src/maps/sock_hash.rs
Map lookup and deletion can yield stale keys and values by virtue of
sharing a data structure with userspace programs and other BPF programs
which can modify it. However, all accesses remain perfectly safe and will
not cause memory corruption or data races.
> aya-bpf: remove unnecessary unsafe markers on map functions.

- .github/workflows/gen.yml
> ci: Use crabby-the-crab

- xtask/src/codegen/aya.rs
This adds the bindings required by #127 and for a WIP PR I have that re-implements #117 as well as adding freezing of ".rodata" maps.
> codegen: Add more bindings

- .github/workflows/gen.yml
> .github: force push to codegen branch

- aya/src/generated/btf_internal_bindings.rs
- aya/src/generated/linux_bindings_aarch64.rs
- aya/src/generated/linux_bindings_armv7.rs
- aya/src/generated/linux_bindings_x86_64.rs
- aya/src/obj/btf/relocation.rs
- bpf/aya-bpf-bindings/src/aarch64/helpers.rs
- bpf/aya-bpf-bindings/src/armv7/helpers.rs
- bpf/aya-bpf-bindings/src/x86_64/helpers.rs
**Automated pull request**<br><br>Update libbpf to 19656636a9b9a2de1f71fa3135709295c16701cc
> Update libbpf to 19656636a9b9a2de1f71fa3135709295c16701cc

- .github/changelog-base.json
- .github/prep-changelog-config.sh
- .github/workflows/release.yml
> ci: Add autogenerated release notes

- .github/changelog-base.json
> ci: Add dependencies/codegen/docs to rel notes

- aya/src/generated/linux_bindings_aarch64.rs
- aya/src/generated/linux_bindings_armv7.rs
- aya/src/generated/linux_bindings_x86_64.rs
**Automated pull request**<br><br>Update libbpf to 22411acc4b2c846868fd570b2d9f3b016d2af2cb
> Update libbpf to 22411acc4b2c846868fd570b2d9f3b016d2af2cb

- aya/src/programs/mod.rs
This re-uses `ProgramInfo` to allow for an `fd` to a pinned program to be obtained from it's id.
> aya: Retrieve program from pinned path

- aya/src/generated/linux_bindings_aarch64.rs
- aya/src/generated/linux_bindings_armv7.rs
- aya/src/generated/linux_bindings_x86_64.rs
**Automated pull request**<br><br>Update libbpf to be89b28f96be426e30a2b0c5312d13b30ee518c7
> Update libbpf to be89b28f96be426e30a2b0c5312d13b30ee518c7

- aya/src/bpf.rs
- aya/src/generated/mod.rs
- aya/src/lib.rs
- aya/src/maps/mod.rs
- aya/src/maps/perf/perf_buffer.rs
- aya/src/maps/sock/mod.rs
- aya/src/obj/btf/btf.rs
- aya/src/programs/extension.rs
- aya/src/programs/kprobe.rs
- aya/src/programs/mod.rs
- aya/src/programs/perf_event.rs
- aya/src/programs/probe.rs
- aya/src/programs/sk_skb.rs
- aya/src/programs/socket_filter.rs
- aya/src/programs/tc.rs
- aya/src/programs/trace_point.rs
- aya/src/programs/uprobe.rs
- aya/src/programs/xdp.rs
> aya: document the public api

- aya/src/obj/btf/btf.rs
- aya/src/obj/btf/types.rs
The union of `size` and `type` is unused in BTF_KIND_ARRAY.
Type information of elements is in the btf_array struct that follows in
the type_ field while the index type is in the index_type field.
For BTF_KIND_INT, only the offset should be compared and size and
signedness should be ignored.
> aya: Fix BTF type resolution for Arrays and Ints

- aya/src/programs/mod.rs
> aya: Fix name truncation

- aya/src/bpf.rs
- aya/src/programs/mod.rs
- aya/src/sys/bpf.rs
Currently errors can occur if the verifier output is > buffer as we get
ENOSPC. We should only provide a log_buf if initial load failed, then
retry up to 10 times to get full verifier output.
> aya: Fix BTF verifier output

- aya/src/obj/mod.rs
- aya/src/obj/relocation.rs
This is based on https://github.com/aya-rs/aya/pull/175
Handle relocations against .text symbols in all instructions not just calls. Makes it so that let x = &some_function triggers linking of some_function in the current program and handles the resulting relocation accordingly.
Among other things, enables the use of bpf_for_each_map_elem.
> relocate .text references

- aya/src/obj/btf/btf.rs
This replaces the / character with a . which is allowed in the kernel
names. Not allowing a forward slash is perhaps a kernel bug, but lets
fix it up here as it's commonly used for Aya
> btf: Replace / in DATASEC before load to kernel

- .github/workflows/build-aya.yml
- test/.gitignore
- test/README.md
- test/cases/000_smoke/000_xdp/pass.ebpf.rs
- test/cases/000_smoke/000_xdp/pass.rs
- test/cases/000_smoke/000_xdp/test.sh
- test/cases/000_smoke/group.sh
- test/cases/010_load/000_name/name_test.ebpf.rs
- test/cases/010_load/000_name/name_test.rs
- test/cases/010_load/000_name/test.sh
- test/cases/010_load/group.sh
- test/cases/_lib/lib.sh
- test/cases/group.sh
This uses a mix of rust-script, bash, qemu and a test runner called RTF
to add a regression test suite.
> test: Add regression tests

- .github/workflows/build-aya.yml
- .github/workflows/images.yml
- images/Dockerfile.rtf
- test/README.md
- test/cases/000_smoke/000_xdp/test.sh
- test/cases/000_smoke/010_ext/ext.bpf.c
- test/cases/000_smoke/010_ext/ext.rs
- test/cases/000_smoke/010_ext/main.bpf.c
- test/cases/000_smoke/010_ext/test.sh
- test/cases/_lib/compile-ebpf.ers
- test/cases/_lib/lib.sh
1. Ability to compile C code :tada: (thanks @vadorovsky as I borrowed this from lockc)
2. A test for BPF_PROG_TYPE_EXT
3. A utility to check minimum kernel version on a test
Closes: #180
> Regression Test Framework Improvements

- .github/workflows/images.yml
> ci: Fix image build workflow

- bpf/aya-bpf/src/maps/lpm_trie.rs
- bpf/aya-bpf/src/maps/mod.rs
cc @alessandrod @dave-tucker @vadorovsky
> Add LPMTrie Map to aya-bpf for BPF programs

- aya/src/programs/probe.rs
> clippy: Fix lint against latest nightly

- aya/src/programs/cgroup_skb.rs
- aya/src/programs/extension.rs
- aya/src/programs/fentry.rs
- aya/src/programs/fexit.rs
- aya/src/programs/kprobe.rs
- aya/src/programs/links.rs
- aya/src/programs/lirc_mode2.rs
- aya/src/programs/lsm.rs
- aya/src/programs/mod.rs
- aya/src/programs/perf_attach.rs
- aya/src/programs/perf_event.rs
- aya/src/programs/raw_trace_point.rs
- aya/src/programs/sk_msg.rs
- aya/src/programs/sk_skb.rs
- aya/src/programs/sock_ops.rs
- aya/src/programs/socket_filter.rs
- aya/src/programs/tc.rs
- aya/src/programs/tp_btf.rs
- aya/src/programs/trace_point.rs
- aya/src/programs/uprobe.rs
- aya/src/programs/xdp.rs
> aya: Implement forget_link

- xtask/src/docs/mod.rs
- xtask/src/main.rs
> xtask: Add docs build

- .github/workflows/build-aya-bpf.yml
- .github/workflows/build-aya.yml
- .github/workflows/images.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- README.md
- netlify.toml
This PR rearranges the README with some big badges to make the links more prominent.
It also adds redirects for the Netlify docs to default to `aya`.
Hopefully this will also show a deploy preview :crossed_fingers:
> Add Netlify Config and Update README

- aya/src/generated/linux_bindings_aarch64.rs
- aya/src/generated/linux_bindings_armv7.rs
- aya/src/generated/linux_bindings_x86_64.rs
- bpf/aya-bpf-bindings/src/aarch64/bindings.rs
- bpf/aya-bpf-bindings/src/aarch64/getters.rs
- bpf/aya-bpf-bindings/src/aarch64/helpers.rs
- bpf/aya-bpf-bindings/src/armv7/bindings.rs
- bpf/aya-bpf-bindings/src/armv7/getters.rs
- bpf/aya-bpf-bindings/src/armv7/helpers.rs
- bpf/aya-bpf-bindings/src/x86_64/bindings.rs
- bpf/aya-bpf-bindings/src/x86_64/getters.rs
- bpf/aya-bpf-bindings/src/x86_64/helpers.rs
**Automated pull request**<br><br>Update libbpf to 86eb09863c1c0177e99c2c703092042d3cdba910
> Update libbpf to 86eb09863c1c0177e99c2c703092042d3cdba910

- aya/src/programs/cgroup_sock_addr.rs
- xtask/src/docs/mod.rs
> xtask: Add all crates to sidebar

- aya/src/bpf.rs
- aya/src/maps/perf/perf_buffer.rs
- aya/src/obj/mod.rs
- aya/src/sys/netlink.rs
- bpf/aya-bpf/src/maps/mod.rs
> clippy: fix new lints on nightly

- xtask/src/codegen/aya.rs
This was separated out from #294 to run the codegen from the CI.
> Codegen changes for RingBuf

- aya/src/generated/linux_bindings_aarch64.rs
- aya/src/generated/linux_bindings_armv7.rs
- aya/src/generated/linux_bindings_riscv64.rs
- aya/src/generated/linux_bindings_x86_64.rs
**Automated pull request**<br><br>Update libbpf to 4eb6485c08867edaa5a0a81c64ddb23580420340
> Update libbpf to 4eb6485c08867edaa5a0a81c64ddb23580420340

- xtask/src/docs/mod.rs
> docs: Merge search indexes

- aya/src/programs/mod.rs
> aya: Unload programs on drop

- .github/workflows/build-aya-bpf.yml
- .github/workflows/build-aya.yml
- bpf/aya-bpf-bindings/build.rs
- bpf/aya-bpf-cty/build.rs
- bpf/aya-bpf/build.rs
- bpf/aya-bpf/src/args.rs
> Enable CI for all supported architectures

- aya-gen/src/generate.rs
- aya/src/maps/map_lock.rs
- aya/src/obj/btf/types.rs
- aya/src/obj/mod.rs
> clippy: Fix latest nightly lints

- aya/src/programs/mod.rs
Kernels before 5.11 don't use cgroup accounting, so they might reach the
RLIMIT_MEMLOCK when creating maps. After this change, we raise a warning
recommending to raise the RLIMIT_MEMLOCK.
> aya: Raise the warning when RMILIT_MEMLOCK is not RLIM_INFINITY

- bpf/aya-bpf/src/helpers.rs
This change adds two new helpers:
* bpf_probe_read_user_str_bytes
* bpf_probe_read_kernel_str_bytes
Those new helpers are returning a bytes slice (`&[u8]`) with a length
equal to the length of probed, null-terminated string. When using those
helpers, users don't have to manually check for length and create such
slices themselves. They also make converting to `str` way more
convenient, for example:
```rust
let my_str = unsafe {
core::str::from_utf8_unchecked(
bpf_probe_read_user_str_bytes(user_ptr, &mut buf)?
)
};
```
This change also deprecates the old helpers, since their names are
confusing (they have nothing to do with Rust `str`) and using them
requires writing boilerplate code (for checking the length and making
eBPF verifier happy):
* bpf_probe_read_user_str
* …
> bpf(helpers): Add *_str_bytes helpers

- bpf/aya-bpf/src/programs/sk_buff.rs
This new method allows to load bytes into the given bytes slice, not
requiring to alloate the memory on stack. It can be used with
PerCpuArrays.
Example:
https://github.com/vadorovsky/aya-examples/blob/main/tc-bytes/tc-bytes-ebpf/src/main.rs
> bpf: Add `load_bytes` method to SKB context

- aya/src/programs/tc.rs
- aya/src/sys/netlink.rs
Addresses issue #358
The SchedClassifier attach function does not currently allow the priority (aka preference) of a classifier program to be explicitly set. Instead, the underlying netlink_qdisc_attach function defaults the priority to zero which tells the system to assign it the next highest priority for the given qdisc. It is useful to be able to explicitly control the order in which filters are executed and also to be able to insert new filters into an existing set at less than the highest priority.
This change adds support for setting the priority explicitly.
Note: aya-template will also need to be updated to add the new parameter.
Signed-off-by: Andre Fredette <afredette@redhat.com>
> Add support for setting priority for classifier programs

- xtask/src/run.rs
@anfredette this should fix the issue you had running the tests.
> xtask: Fix integration-test command

- bpf/aya-bpf/src/programs/sk_buff.rs
The pull_data method is used to ensure that all the required bytes
are available in the linear portion of the skb.
Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>
> aya-bpf/programs: Add `pull_data` method to SKB context

- xtask/src/codegen/aya.rs
> codegen: Add bpf_map_info and bpf_link_info

- xtask/src/codegen/aya.rs
> codgen: Add bpf_link_type

- aya/src/generated/linux_bindings_aarch64.rs
- aya/src/generated/linux_bindings_armv7.rs
- aya/src/generated/linux_bindings_riscv64.rs
- aya/src/generated/linux_bindings_x86_64.rs
**Automated pull request**<br><br>Update libbpf to efd33720cdf4a0049323403df5daad0e9e894b3d
> Update libbpf to efd33720cdf4a0049323403df5daad0e9e894b3d

- test/run.sh
> tests: Use Fedora 36

- aya/src/obj/relocation.rs
- aya/src/sys/perf_event.rs
> Fix clippy warnings

- aya/src/programs/uprobe.rs
See https://github.com/foniod/redbpf/pull/308 for a similar change.
> Resolve symbol address for PIE executables

- aya-log/src/lib.rs
This was broken in d6cb1a16ad0f8df483e2234fb01ab55bdbeaa8b8.
> Don't panic in init when bpf programs don't log

- aya-tool/src/generate.rs
- aya/src/obj/btf/types.rs
- xtask/src/docs/mod.rs
Computing pointer sizes was broken in #285
> btf: fix regression computing pointer sizes

- bpf/aya-bpf/src/maps/array.rs
> aya-bpf/maps: Add `get_ptr` and `get_mut_ptr` methods to Array

- aya-obj/src/generated/linux_bindings_aarch64.rs
- aya-obj/src/generated/linux_bindings_armv7.rs
- aya-obj/src/generated/linux_bindings_riscv64.rs
- aya-obj/src/generated/linux_bindings_x86_64.rs
- aya-obj/src/maps.rs
- bpf/aya-bpf-bindings/src/aarch64/bindings.rs
- bpf/aya-bpf-bindings/src/aarch64/helpers.rs
- bpf/aya-bpf-bindings/src/armv7/bindings.rs
- bpf/aya-bpf-bindings/src/armv7/helpers.rs
- bpf/aya-bpf-bindings/src/riscv64/bindings.rs
- bpf/aya-bpf-bindings/src/riscv64/helpers.rs
- bpf/aya-bpf-bindings/src/x86_64/bindings.rs
- bpf/aya-bpf-bindings/src/x86_64/helpers.rs
**Automated pull request**<br><br>Update libbpf to 3423d5e7cdab356d115aef7f987b4a1098ede448
> Update libbpf to 3423d5e7cdab356d115aef7f987b4a1098ede448

- aya-log/Cargo.toml
- aya/Cargo.toml
- test/integration-test/Cargo.toml
> Update Tokio and inventory

- .github/workflows/build-aya-bpf.yml
- .github/workflows/build-aya.yml
- netlify.toml
- xtask/src/build_ebpf.rs
- xtask/src/docs/mod.rs
The issues with core::sync::atomic got fixed.
> Unpin Rust nightly

- aya/src/sys/bpf.rs
fix a bug which resulted in failure to load maps->  
```
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_PERF_EVENT_ARRAY, key_size=4, value_size=4, max_entries=24, map_flags=0, inner_map_fd=0, map_name="ingress_node_fi", map_ifindex=0, btf_fd=11, btf_key_type_id=6, btf_value_type_id=6, btf_vmlinux_value_type_id=0, map_extra=0}, 144) = -1 ENOTSUPP (Unknown error 524)
```
Specifically it is the same fix deployed by libbpf, more information can be found here https://github.com/libbpf/libbpf/issues/355
> Support BTF key/value specification for all maps

- README.md
Quick little fix for https://github.com/badges/shields/issues/8671 :)
> Fix Aya build badge

- aya/src/bpf.rs
- aya/src/util.rs
Alternative to https://github.com/aya-rs/aya/pull/555
> aya: make it possible to use set_global() with slices of Pod(s)

- aya/src/programs/utils.rs
Fixes issue described in: https://github.com/aya-rs/aya/issues/556
> Add check for empty tracefs mounts

- aya-obj/src/btf/btf.rs
This fix the following issues:
- Previously the DATASEC name wasn't sanitized resulting on "Invalid name" returned by old kernels.
- The newly created BTF struct had a size of 0 making old kernels refuse it.
This was tested on Debian 10 with kernel 4.19.0-21.
> aya-obj: fix DATASEC to STRUCT conversion

- aya-obj/src/btf/btf.rs
- bpf/aya-bpf/src/lib.rs
- fixing memset return value for proper BTF validation
- fixing memset + memcpy linkage type when loading BPF program
> Fix builtin linkage

- .github/workflows/build-aya-bpf.yml
- .github/workflows/build-aya.yml
- .github/workflows/gen.yml
- .github/workflows/lint.yml
See https://github.com/actions-rs/toolchain/issues/216; actions-rs seems
to be unmaintained.
> Replace actions-rs/toolchain with dtolnay/rust-toolchain

- aya-log-common/src/lib.rs
- aya-log-ebpf-macros/src/expand.rs
- bpf/aya-log-ebpf/src/lib.rs
- test/integration-ebpf/src/log.rs
> aya-log-ebpf: avoid requiring Copy

- aya/src/programs/uprobe.rs
This fix uprobe support on Debian 10. (and possibly others)
This implement support to parse the original libc5 format.
> aya: Add support for old ld.so.cache format

- xtask/src/docs.rs
> site: generate docs for logging crates

- test/integration-test/build.rs
It turns out that cargo ignores rerun-if-changed directives that point
into $CARGO_HOME; use a symlink to trick cargo into respecting my
authoritah.
> integration-test: invalidate on bpf-linker

- .github/workflows/gen.yml
- .gitmodules
- test/integration-test/Cargo.toml
- test/integration-test/build.rs
- test/run.sh
- xtask/src/codegen/aya.rs
- xtask/src/codegen/aya_bpf_bindings.rs
- xtask/src/codegen/mod.rs
- xtask/src/docs.rs
- xtask/src/lib.rs
- xtask/src/main.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/664)
> xtask: ensure libbpf submodule is initialized

- xtask/src/run.rs
Extracted from https://github.com/aya-rs/aya/pull/661. Useful for https://github.com/aya-rs/bpf-linker/pull/72.
> xtask: allow arbitrary flags to cargo build

- .github/workflows/ci.yml
Human time is more precious than computer time.
> github: parallel all the CI

- .vscode/settings.json
- xtask/Cargo.toml
- xtask/src/public_api.rs
- public-api: ignore fixtures in git grep
- public-api: simplify and improve output
> public api followup

- aya/src/programs/uprobe.rs
This code badly needs tests :(
> aya: preallocate the vector

- aya-obj/src/btf/btf.rs
We already have a mutable reference in scope, use it where possible.
> aya-obj: s/types.types[i]/*t/ where possible

- xtask/src/run.rs
Seems unclear whether kernel panics go to stdout or stderr, so do them
both.
> xtask: watch for kernel panic in stdout too

- xtask/public-api/aya.txt
Changes to the bitflags crate changed some of our public api signature.
> xtask: Fix aya public-api

- .github/workflows/ci.yml
- aya-obj/include/linux_wrapper.h
- bpf/aya-bpf-bindings/include/bindings.h
> .github: Add clang-format

- aya/src/programs/extension.rs
- aya/src/programs/mod.rs
- aya/src/sys/bpf.rs
- test/integration-test/src/tests/smoke.rs
- xtask/public-api/aya-log.txt
- xtask/public-api/aya-obj.txt
- xtask/public-api/aya-tool.txt
- xtask/public-api/aya.txt
Contains minor extractions from #723.
> programs: `ProgramData::attach_prog_fd` is owned

- .github/workflows/ci.yml
- Cargo.toml
- xtask/src/lib.rs
- xtask/src/public_api.rs
- xtask/src/run.rs
> github: fix CI

- aya/src/programs/xdp.rs
- aya/src/sys/netlink.rs
> netlink: use OwnedFd

- aya/src/programs/links.rs
- aya/src/programs/lirc_mode2.rs
- aya/src/sys/bpf.rs
> programs: ProgAttachLink and LircLink hold owned FDs

- test/integration-test/src/tests/xdp.rs
See individual commits.
/cc @Tuetuopay
> integration/xdp: increase timeout to 60 seconds

- xtask/public-api/aya-bpf-bindings.txt
- xtask/public-api/aya-log-common.txt
- xtask/public-api/aya-log-parser.txt
- xtask/public-api/aya-obj.txt
- xtask/public-api/aya.txt
See https://github.com/rust-lang/rust/commit/58a80c85b9323e59e1b7e744d6.
> public-api: bless with new nightly

- test/README.md
- Update the list of required packages.
- Update the command for executing tests in a VM.
> tests: update instructions on setting up and running tests

- xtask/src/run.rs
See
https://github.com/aya-rs/bpf-linker/actions/runs/7067897954/job/19241830198
> xtask: terminate QEMU on "RCU grace-period kthread stack dump"

- aya/src/programs/cgroup_device.rs
- aya/src/programs/links.rs
- xtask/public-api/aya.txt
This follows closely the existing `LircMode2::query`.
> Add `CgroupDevice::query`

- aya/src/maps/mod.rs
- aya/src/maps/ring_buf.rs
- aya/src/programs/mod.rs
- aya/src/util.rs
This was failing the docs build.
> chore: Fix unused_qualifications lints

- xtask/public-api/aya.txt
Auto trait bounds have changed in one of:
- https://github.com/rust-lang/rust/pull/123340.
- https://github.com/rust-lang/rust/pull/123375.
> public-api: regenerate

- ebpf/aya-ebpf/src/helpers.rs
- test/integration-test/src/tests/btf_relocations.rs
- **Appease clippy**
- **Revert "Disable false-positive clippy lint"**
> Appease clippy

- ebpf/aya-ebpf-bindings/build.rs
- ebpf/aya-ebpf-bindings/src/lib.rs
- ebpf/aya-ebpf-cty/build.rs
- ebpf/aya-ebpf-cty/src/lib.rs
- ebpf/aya-ebpf/build.rs
- ebpf/aya-ebpf/src/lib.rs
- **Deny warnings**
- **Allowlist expected cfgs**
> Allow expected cfgs

- aya/src/lib.rs
Nightly added stuff to the prelude.
> Don't deny unused_qualifications

- aya-obj/src/generated/linux_bindings_aarch64.rs
- aya-obj/src/generated/linux_bindings_armv7.rs
- aya-obj/src/generated/linux_bindings_powerpc64.rs
- aya-obj/src/generated/linux_bindings_riscv64.rs
- aya-obj/src/generated/linux_bindings_s390x.rs
- aya-obj/src/generated/linux_bindings_x86_64.rs
- xtask/public-api/aya-obj.txt
**Automated pull request**<br><br>Update libbpf to 686f600bca59e107af4040d0838ca2b02c14ff50
> Update libbpf to 686f600bca59e107af4040d0838ca2b02c14ff50

- aya-log/src/lib.rs
See https://github.com/rust-lang/rust/commit/31fe9628cf830a08e7194a446f66c668aaea86e9.
> Remove unused `allow(dead_code)`

- ebpf/aya-ebpf-bindings/src/aarch64/bindings.rs
- ebpf/aya-ebpf-bindings/src/armv7/bindings.rs
- ebpf/aya-ebpf-bindings/src/powerpc64/bindings.rs
- ebpf/aya-ebpf-bindings/src/riscv64/bindings.rs
- ebpf/aya-ebpf-bindings/src/s390x/bindings.rs
- ebpf/aya-ebpf-bindings/src/x86_64/bindings.rs
- xtask/public-api/aya-ebpf-bindings.txt
**Automated pull request**<br><br>Update libbpf to b07dfe3b2a6cb0905e883510f22f9f7c0bb66d0d
> Update libbpf to b07dfe3b2a6cb0905e883510f22f9f7c0bb66d0d

- aya/src/programs/sock_ops.rs
- xtask/public-api/aya.txt
See: https://github.com/aya-rs/aya/issues/987
> aya: use FdLink in SockOps programs

- Cargo.toml
- aya-log/src/lib.rs
- aya/Cargo.toml
- aya/src/bpf.rs
- aya/src/maps/array/per_cpu_array.rs
- aya/src/maps/hash_map/per_cpu_hash_map.rs
- aya/src/maps/mod.rs
- aya/src/maps/perf/async_perf_event_array.rs
- aya/src/maps/perf/perf_event_array.rs
- aya/src/maps/xdp/cpu_map.rs
- aya/src/programs/perf_event.rs
- aya/src/programs/uprobe.rs
- aya/src/programs/utils.rs
- aya/src/util.rs
- xtask/public-api/aya.txt
> Avoid intermediate allocations in parse_cpu_ranges

- Cargo.toml
- aya/Cargo.toml
- aya/src/util.rs
> perf: cache `nr_cpus` in a thread_local

- .github/scripts/download_kernel_images.sh
- .github/workflows/ci.yml
> ci: automatically download latest kernel revs

- .github/workflows/ci.yml
This is annoying and I'd like to stop doing it.
> ci: automatically open PRs to update public API

- aya/src/programs/cgroup_device.rs
- aya/src/programs/cgroup_skb.rs
- aya/src/programs/cgroup_sock.rs
- aya/src/programs/cgroup_sock_addr.rs
- aya/src/programs/cgroup_sockopt.rs
- aya/src/programs/cgroup_sysctl.rs
- aya/src/programs/extension.rs
- aya/src/programs/fentry.rs
- aya/src/programs/fexit.rs
- aya/src/programs/iter.rs
- aya/src/programs/kprobe.rs
- aya/src/programs/links.rs
- aya/src/programs/lirc_mode2.rs
- aya/src/programs/lsm.rs
- aya/src/programs/mod.rs
- aya/src/programs/perf_event.rs
- aya/src/programs/raw_trace_point.rs
- aya/src/programs/sk_lookup.rs
- aya/src/programs/sk_msg.rs
- aya/src/programs/sk_skb.rs
- aya/src/programs/sock_ops.rs
- aya/src/programs/socket_filter.rs
- aya/src/programs/tc.rs
- aya/src/programs/tp_btf.rs
- aya/src/programs/trace_point.rs
- aya/src/programs/uprobe.rs
- aya/src/programs/xdp.rs
- xtask/public-api/aya.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1094)
> Define `{detach,take_link}` in macro when possible

- Cargo.toml
- clippy.sh
- test/integration-common/Cargo.toml
- test/integration-common/src/lib.rs
- test/integration-ebpf/Cargo.toml
- test/integration-ebpf/src/bpf_probe_read.rs
- test/integration-ebpf/src/ring_buf.rs
- test/integration-ebpf/src/strncmp.rs
- test/integration-test/Cargo.toml
- test/integration-test/src/tests/bpf_probe_read.rs
- test/integration-test/src/tests/ring_buf.rs
- test/integration-test/src/tests/strncmp.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1102)
> Extract integration-common for shared types

- aya-build/Cargo.toml
- aya-build/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1105)
> Add description

- Cargo.toml
- aya-ebpf-macros/Cargo.toml
- aya-ebpf-macros/src/btf_tracepoint.rs
- aya-ebpf-macros/src/cgroup_device.rs
- aya-ebpf-macros/src/cgroup_skb.rs
- aya-ebpf-macros/src/cgroup_sock.rs
- aya-ebpf-macros/src/cgroup_sock_addr.rs
- aya-ebpf-macros/src/cgroup_sockopt.rs
- aya-ebpf-macros/src/cgroup_sysctl.rs
- aya-ebpf-macros/src/fentry.rs
- aya-ebpf-macros/src/fexit.rs
- aya-ebpf-macros/src/kprobe.rs
- aya-ebpf-macros/src/lib.rs
- aya-ebpf-macros/src/lsm.rs
- aya-ebpf-macros/src/map.rs
- aya-ebpf-macros/src/perf_event.rs
- aya-ebpf-macros/src/raw_tracepoint.rs
- aya-ebpf-macros/src/sk_lookup.rs
- aya-ebpf-macros/src/sk_msg.rs
- aya-ebpf-macros/src/sk_skb.rs
- aya-ebpf-macros/src/sock_ops.rs
- aya-ebpf-macros/src/socket_filter.rs
- aya-ebpf-macros/src/tc.rs
- aya-ebpf-macros/src/tracepoint.rs
- aya-ebpf-macros/src/uprobe.rs
- aya-ebpf-macros/src/xdp.rs
proc-macro-error is unmaintained.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1108)
> Replace proc-macro-error with proc-macro2-diagnostics

- .github/workflows/ci.yml
- Cargo.toml
- xtask/Cargo.toml
- xtask/src/run.rs
See commit message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1115)
> ci: download gen_init_cpio with authentication

- aya-log-parser/src/lib.rs
- aya-obj/src/btf/relocation.rs
- aya/src/maps/lpm_trie.rs
- aya/src/sys/mod.rs
- ebpf/aya-ebpf/src/maps/lpm_trie.rs
- ebpf/aya-ebpf/src/maps/perf/perf_event_array.rs
- ebpf/aya-ebpf/src/maps/perf/perf_event_byte_array.rs
- xtask/public-api/aya-ebpf.txt
- xtask/public-api/aya.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1121)
> chore: Fix cippy errors

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1147)
> Update public-api to 0.43.0

- .github/workflows/gen.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1152)
> ci: Install libc6-dev-mips-cross for codegen

- aya-obj/src/generated/linux_bindings_aarch64.rs
- aya-obj/src/generated/linux_bindings_armv7.rs
- aya-obj/src/generated/linux_bindings_mips.rs
- aya-obj/src/generated/linux_bindings_powerpc64.rs
- aya-obj/src/generated/linux_bindings_riscv64.rs
- aya-obj/src/generated/linux_bindings_s390x.rs
- aya-obj/src/generated/linux_bindings_x86_64.rs
- xtask/public-api/aya-obj.txt
**Automated pull request**<br><br>Update libbpf to d4a841a32b04d69194ab5bdac359a51938a206ce
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1158)
> Update libbpf to d4a841a32b04d69194ab5bdac359a51938a206ce

- .github/workflows/gen.yml
Updated to match the commit message
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1159)
> ci: Update codegen PR template

- Cargo.toml
cc @altugbozkurt07
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1175)
> Update public-api to 0.44.0

- Cargo.toml
Fixes #1178.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1179)
> Correctly specify git dependency

- aya-tool/src/rustfmt.rs
- aya/src/maps/ring_buf.rs
- aya/src/programs/probe.rs
- aya/src/programs/trace_point.rs
- aya/src/programs/utils.rs
- aya/src/sys/netlink.rs
- xtask/public-api/aya.txt
While I'm here convert a String to a PathBuf in an error to avoid lossy
conversions.
See https://rust-lang.github.io/rust-clippy/master/index.html#io_other_error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1192)
> *: appease clippy

- aya-obj/src/btf/btf.rs
- aya-obj/src/obj.rs
- aya/src/maps/bloom_filter.rs
- aya/src/maps/lpm_trie.rs
- aya/src/maps/mod.rs
- aya/src/maps/perf/perf_buffer.rs
- aya/src/maps/ring_buf.rs
- aya/src/sys/mod.rs
- aya/src/sys/netlink.rs
- xtask/public-api/aya.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1190)
> Un-ignore tests under Miri

- aya/src/util.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1195)
> aya: add TODO to remove once_cell

- ebpf/aya-ebpf/src/programs/xdp.rs
- test/integration-ebpf/src/redirect.rs
- test/integration-test/src/tests/xdp.rs
- xtask/public-api/aya-ebpf.txt
This is #846. I'm recreating it because I am unable to push changes to that PR
due to branch protection (the author created the PR using their main branch).
cc @arctic-alpaca
Closes #846.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1200)
> Improve AF_XDP test

- aya/src/programs/uprobe.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1205)
> Avoid allocations when parsing /proc/{pid}/maps

- Cargo.toml
Follow up #1208
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1217)
> Update octorust to 0.10

- .github/dependabot.yml
- .taplo.toml
- Cargo.toml
- aya-build/Cargo.toml
- aya-ebpf-macros/Cargo.toml
- aya-log-common/Cargo.toml
- aya-log-ebpf-macros/Cargo.toml
- aya-log-parser/Cargo.toml
- aya-log/Cargo.toml
- aya-obj/Cargo.toml
- aya-tool/Cargo.toml
- aya/Cargo.toml
- aya/src/maps/info.rs
- ebpf/aya-ebpf-bindings/Cargo.toml
- ebpf/aya-ebpf-cty/Cargo.toml
- ebpf/aya-ebpf/Cargo.toml
- ebpf/aya-log-ebpf/Cargo.toml
- init/Cargo.toml
- netlify.toml
- release.toml
- test/integration-common/Cargo.toml
- test/integration-ebpf/Cargo.toml
- test/integration-test/Cargo.toml
- test/integration-test/src/tests/info.rs
- test/integration-test/src/utils.rs
- xtask/Cargo.toml
Addressing my own comments from #1007.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1219)
> integration-test: minor cleanup

- aya-build/src/lib.rs
- test/integration-test/build.rs
- xtask/public-api/aya-build.txt
Resolves: #1226
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1228)
> feat(aya-build): allow setting Rust version

- test/integration-test/build.rs
- xtask/src/codegen/aya_ebpf_bindings.rs
- xtask/src/lib.rs
Before that, the same code was repeated twice in different places.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1236)
> xtask: Move libbpf header installation logic to a helper function

- Cargo.toml
- aya-build/src/lib.rs
Closes #1227.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1250)
> aya-build: enable BTF

- ebpf/aya-ebpf/src/lib.rs
- xtask/public-api/aya-ebpf.txt
Closes #1254.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1255)
> aya-ebpf: put mem{set,move,cpy} behind cfg(target_arch = "bpf")

- aya-ebpf-macros/src/btf_tracepoint.rs
- aya-ebpf-macros/src/fentry.rs
- aya-ebpf-macros/src/fexit.rs
- aya-ebpf-macros/src/kprobe.rs
- aya-ebpf-macros/src/lsm.rs
- aya-ebpf-macros/src/raw_tracepoint.rs
- aya-ebpf-macros/src/uprobe.rs
- aya-log/src/lib.rs
- aya-obj/src/btf/btf.rs
- aya-obj/src/obj.rs
- aya-obj/src/relocation.rs
- aya/src/bpf.rs
- aya/src/maps/hash_map/hash_map.rs
- aya/src/maps/mod.rs
- aya/src/maps/perf/perf_buffer.rs
- aya/src/programs/utils.rs
- aya/src/util.rs
- test-distro/src/depmod.rs
- test-distro/src/init.rs
- test-distro/src/modprobe.rs
- test/integration-ebpf/build.rs
- test/integration-test/src/tests/iter.rs
- xtask/src/lib.rs
- xtask/src/public_api.rs
- xtask/src/run.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1259)
> appease `clippy::uninlined-format-args`

- aya/src/maps/mod.rs
- aya/src/maps/perf/perf_buffer.rs
- aya/src/maps/ring_buf.rs
- aya/src/programs/uprobe.rs
- aya/src/util.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1261)
> aya: uprobe attach: use mmap instead of reading whole binaries to memory

- ebpf/aya-ebpf/build.rs
- ebpf/aya-ebpf/src/lib.rs
- ebpf/aya-ebpf/src/maps/ring_buf.rs
- xtask/public-api/aya-ebpf.txt
- xtask/public-api/aya.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1271)
> aya-ebpf: work around generic_const_exprs regression

- .github/workflows/ci.yml
- .github/workflows/gen.yml
See https://github.com/peter-evans/create-pull-request/issues/48.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1280)
> Use CRABBY_GITHUB_TOKEN for regen PRs

- test-distro/src/init.rs
- test/integration-test/Cargo.toml
- test/integration-test/src/tests/ring_buf.rs
- xtask/src/run.rs
See individual commits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1289)
> integration-test: remove an allocation

- aya/src/programs/uprobe.rs
`construct_debuglink_path()` returns a `Result`, but it doesn't actually do anything that can fail. This means callers must do a useless `unwrap()` to get at the return value.
This fixes the signature to reflect that the function is infallible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1286)
> aya: `construct_debuglink_path()` should be infallible

- aya-log/src/lib.rs
Replace match statement with direct Option comparison for cleaner code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/aya/1299)
> aya-log: simplify map name matching using direct Option comparison
